import path from 'node:path';
import JSZip from 'jszip';
import {SaxesParser} from 'saxes';
import {archivePreflight} from './extract.js';
const escape=(s:string)=>s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const allowed=new Set(['p','div','span','section','article','h1','h2','h3','h4','h5','h6','ul','ol','li','blockquote','strong','em','b','i','sup','sub','table','thead','tbody','tr','td','th','caption','figure','figcaption','pre','code','br','hr']);
function parse(text:string,open:(name:string,a:Record<string,string>)=>void,close:(name:string)=>void,onText:(s:string)=>void){if(/<!DOCTYPE|<!ENTITY/i.test(text))throw new Error('document_declarations_rejected');const p=new SaxesParser({xmlns:false});p.on('opentag',t=>open(t.name.replace(/^.*:/,''),t.attributes as Record<string,string>));p.on('closetag',t=>close(t.name.replace(/^.*:/,'')));p.on('text',onText);p.on('cdata',onText);p.write(text).close();}
function entryPath(base:string,href:string){if(/^[a-z]+:|^\/|\\/i.test(href))throw new Error('external_epub_resource_rejected');const result=path.posix.normalize(path.posix.join(path.posix.dirname(base),decodeURIComponent(href.split('#')[0]!)));if(result.startsWith('../')||result.startsWith('/'))throw new Error('unsafe_epub_resource');return result;}
export async function epubReading(bytes:Buffer){
 archivePreflight(bytes);const zip=await JSZip.loadAsync(bytes);const read=async(name:string)=>{const f=zip.file(name);if(!f)throw new Error('document_part_missing');return f.async('string');};
 if((await read('mimetype')).trim()!=='application/epub+zip'||zip.file('META-INF/encryption.xml'))throw new Error('unsupported_epub');let root='';parse(await read('META-INF/container.xml'),(n,a)=>{if(n==='rootfile')root=entryPath('container',a['full-path']??'');},()=>{},()=>{});
 const manifest=new Map<string,string>(),spine:string[]=[];parse(await read(root),(n,a)=>{if(n==='item'&&a.id&&a.href)manifest.set(a.id,a.href);if(n==='itemref'&&a.idref)spine.push(a.idref);},()=>{},()=>{});if(!spine.length||spine.length>500)throw new Error('epub_spine_limit');const chapters=[];
 for(const id of spine){const location=entryPath(root,manifest.get(id)??'');let html='',skip=0,title='';const images:Array<{token:string;src:string;alt:string}>=[];
 parse(await read(location),(n,a)=>{if(skip){skip++;return;}if(['script','style','iframe','object','embed','svg','math','head','form','audio','video'].includes(n)){skip=1;return;}if(n==='img'){const token=`<!--CNIMAGE${images.length}PLACEHOLDER-->`;images.push({token,src:a.src??'',alt:a.alt??'Image'});html+=token;return;}if(allowed.has(n))html+=`<${n}>`;},n=>{if(skip){skip--;return;}if(allowed.has(n)&&!['br','hr'].includes(n))html+=`</${n}>`;},s=>{if(!skip){html+=escape(s);if(title.length<80)title+=s;}});
 for(const img of images){let replacement=`<p>[Image unavailable: ${escape(img.alt)}]</p>`;try{const file=entryPath(location,img.src),ext=path.posix.extname(file).toLowerCase(),mime=({'.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.gif':'image/gif','.webp':'image/webp'} as Record<string,string>)[ext];const resource=zip.file(file);if(mime&&resource){const data=await resource.async('nodebuffer');if(data.length<=4*1024*1024)replacement=`<img alt="${escape(img.alt)}" src="data:${mime};base64,${data.toString('base64')}">`;}}catch{/* Never fetch external resources. */}html=html.replace(img.token,replacement);}
 if(html.length>16*1024*1024||chapters.reduce((n,c)=>n+c.html.length,0)+html.length>40*1024*1024)throw new Error('epub_reading_limit');
 chapters.push({location,title:title.trim().slice(0,80)||`Chapter ${chapters.length+1}`,html});}return {chapters,warnings:['Safe EPUB rendition: scripts, publisher styles, active objects, MathML and SVG are excluded. Check the downloaded original for omitted content.']};
}
