import {useEffect,useState} from 'react';
import {api} from './client';
type Task={id:string;sourceId:string;status:string;error:string|null;progress:number};
export function Materials({courseId}:{courseId:string}){
 const [tasks,setTasks]=useState<Task[]>([]),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[text,setText]=useState(''),[title,setTitle]=useState('');
 const [sources,setSources]=useState<Array<{id:string;filename:string;revision:number}>>([]);
 const [detail,setDetail]=useState<Awaited<ReturnType<typeof api.materials.detail>>|null>(null);
 const [files,setFiles]=useState<File[]>([]);
 async function refresh(){try{setTasks(await api.materials.tasks(courseId));setSources(await api.materials.list(courseId));}catch{setNotice('Import queue could not be loaded. Check the local service and retry.');}}
 useEffect(()=>{let cancelled=false;void api.materials.tasks(courseId).then(rows=>{if(!cancelled)setTasks(rows);}).catch(()=>{if(!cancelled)setNotice('Import queue could not be loaded.');});void api.materials.list(courseId).then(rows=>{if(!cancelled)setSources(rows);}).catch(()=>undefined);return()=>{cancelled=true;};},[courseId]);
 async function submit(){setBusy(true);setNotice('');const failed:File[]=[];let count=0;try{for(const file of files){try{const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(const byte of bytes)binary+=String.fromCharCode(byte);await api.materials.import(courseId,file.name,btoa(binary));count++;}catch{failed.push(file);}}setFiles(failed);setNotice(`${count} files queued. ${failed.length?`${failed.length} failed; those files remain selected for retry.`:'Originals are saved locally.'}`);await refresh();}finally{setBusy(false);}}
 return <section><div className="page-heading"><div><p className="eyebrow">Your material</p><h1>Sources</h1><p>Import your files or start with your own words. Originals stay on this Mac.</p></div><button disabled={busy} onClick={()=>void refresh()}>Refresh</button></div>
 {notice&&<p className="notice" role="status">{notice}</p>}
 <div className="course-grid"><section className="glass glass-card"><h2>Import files</h2><p>Text, Markdown, PDF, DOCX, DRM-free EPUB, PNG and JPEG. Up to 25 MiB each. Same-name updates are preserved as separate sources.</p><label>Choose files<input type="file" multiple accept=".txt,.md,.pdf,.docx,.epub,.png,.jpg,.jpeg" disabled={busy} onChange={e=>setFiles(Array.from(e.target.files??[]))}/></label><ul>{files.map((f,i)=><li key={`${f.name}:${i}`}>{f.name} · {Math.ceil(f.size/1024)} KiB</li>)}</ul><button className="primary" disabled={busy||!files.length} onClick={()=>void submit()}>{busy?'Importing…':'Import selected files'}</button></section>
 <section className="glass glass-card"><h2>Paste text or write a note</h2><form className="form-stack" onSubmit={e=>{e.preventDefault();setBusy(true);void api.materials.import(courseId,`${title.trim()||'Note'}.txt`,btoa(unescape(encodeURIComponent(text))),'note').then(async()=>{setText('');setTitle('');setNotice('Note queued and original text preserved.');await refresh();}).catch(()=>setNotice('Note could not be saved. Your text is preserved here.')).finally(()=>setBusy(false));}}><label>Title<input maxLength={180} value={title} disabled={busy} onChange={e=>setTitle(e.target.value)}/></label><label>Your text<textarea value={text} disabled={busy} onChange={e=>setText(e.target.value)} required/></label><button className="primary" disabled={busy||!text.trim()}>Save note</button></form></section></div>
 <h2>Saved sources</h2><ul>{sources.map(source=><li key={source.id}><button onClick={()=>void api.materials.detail(courseId,source.id).then(setDetail).catch(()=>setNotice('Source could not be loaded.'))}>{source.filename}</button></li>)}</ul>
 {detail&&<section className="glass glass-card"><h2>{detail.material.filename}</h2><a className="button" href={api.materials.original(courseId,detail.material.id)}>Download original</a>{detail.revisions.length?<><p>Extracted text · verify against your original before using it.</p><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{detail.revisions[0]?.text}</pre><details><summary>Source anchors</summary><pre style={{whiteSpace:'pre-wrap'}}>{detail.revisions[0]?.anchors}</pre></details></>:<p>Text has not been extracted. Use Extract text in the queue, then reopen this source.</p>}</section>}
 <h2>Import queue</h2>{!tasks.length?<p>No imports yet.</p>:<ul>{tasks.map(t=><li key={t.id}><strong>{t.sourceId}</strong> · {t.status} {t.error&&<span>· {t.error}</span>} {t.status==='queued'&&<button disabled={busy} onClick={()=>void api.materials.action(courseId,t.id,'process').then(refresh).catch(()=>setNotice('Extraction could not start.'))}>Extract text</button>} {['queued','running'].includes(t.status)?<button disabled={busy} onClick={()=>void api.materials.action(courseId,t.id,'cancel').then(refresh).catch(()=>setNotice('Cancellation could not be saved. Refresh to see the current state.'))}>Cancel</button>:['failed','cancelled'].includes(t.status)?<button disabled={busy} onClick={()=>void api.materials.action(courseId,t.id,'retry').then(refresh).catch(()=>setNotice('Retry failed. Your original remains saved.'))}>Retry</button>:null}</li>)}</ul>}
 </section>;
}
