import {useCallback,useEffect,useRef,useState} from 'react';
import {api,type MaterialDetail,type MaterialSummary,type LocalIndex} from './client';
type Task={id:string;sourceId:string;status:string;error:string|null;progress:number};
// In-memory drafts survive navigation/theme switches; never stored in browser persistence.
const corrections=new Map<string,{text:string;revision:number}>();
const notes=new Map<string,{title:string;text:string}>();
function message(error:unknown){
 const code=error instanceof Error?error.message:'';
 const labels:Record<string,string>={revision_conflict:'This source changed. Your draft is preserved; reopen the source to compare versions.',index_busy:'An index build is already running.',material_busy:'Cancel or finish extraction before changing this source.',embedding_model_missing:'The local embedding model is missing. Follow the setup guide.',index_course_too_large:'This course exceeds the current local index limit. Split the material into smaller courses.',deletion_confirmation_required:'Enter the exact filename and acknowledge separate backups.',original_checksum_mismatch:'The original file has changed outside the app. Restore it before exporting or deleting.'};
 return labels[code]??`Operation failed (${code||'local service unavailable'}). Your unsaved text is preserved. Retry when the service is available.`;
}
function download(value:unknown,name:string){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function Materials({courseId}:{courseId:string}){
 const [tasks,setTasks]=useState<Task[]>([]),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const [text,setText]=useState(notes.get(courseId)?.text??''),[title,setTitle]=useState(notes.get(courseId)?.title??'');
 const [sources,setSources]=useState<MaterialSummary[]>([]),[detail,setDetail]=useState<MaterialDetail|null>(null);
 const [files,setFiles]=useState<File[]>([]),[edit,setEdit]=useState(''),[expected,setExpected]=useState(0),[reviewed,setReviewed]=useState(false);
 const [selected,setSelected]=useState<string[]>([]),[trash,setTrash]=useState(false),[page,setPage]=useState(1),[previewError,setPreviewError]=useState(false);
 const [deleting,setDeleting]=useState<MaterialSummary|null>(null),[confirmation,setConfirmation]=useState(''),[ack,setAck]=useState(false);
 const [index,setIndex]=useState<LocalIndex|null>(null);
 const mounted=useRef(true),openSequence=useRef(0);
 const refresh=useCallback(async()=>{
  const [t,s,i]=await Promise.all([api.materials.tasks(courseId),api.materials.list(courseId),api.materials.index(courseId)]);
  if(mounted.current){setTasks(t);setSources(s);setIndex(i);setSelected(ids=>ids.filter(id=>s.some(m=>m.id===id&&!m.trashedAt&&!m.deletedAt)));}
 },[courseId]);
 useEffect(()=>{mounted.current=true;void refresh().catch(e=>setNotice(message(e)));const timer=setInterval(()=>void refresh().catch(()=>undefined),2000);return()=>{mounted.current=false;clearInterval(timer);};},[refresh]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if([...corrections.keys()].some(k=>k.startsWith(`${courseId}:`))||notes.get(courseId)?.text){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[courseId]);
 async function run(action:()=>Promise<unknown>,success?:string){setBusy(true);setNotice('');try{await action();await refresh();if(success)setNotice(success);}catch(e){setNotice(message(e));}finally{if(mounted.current)setBusy(false);}}
 async function openSource(id:string){const seq=++openSequence.current;try{const d=await api.materials.detail(courseId,id);if(!mounted.current||seq!==openSequence.current)return;setDetail(d);const draft=corrections.get(`${courseId}:${id}`);setEdit(draft?.text??d.revisions[0]?.text??'');setExpected(draft?.revision??d.material.revision);setReviewed(false);setPage(1);setPreviewError(false);if(draft&&draft.revision!==d.material.revision)setNotice('A newer revision exists. Your older draft is preserved. Compare the history before discarding it.');}catch(e){setNotice(message(e));}}
 function changeNote(nextTitle:string,nextText:string){setTitle(nextTitle);setText(nextText);notes.set(courseId,{title:nextTitle,text:nextText});}
 async function submitFiles(){await run(async()=>{const failed:File[]=[];let count=0;for(const file of files){try{const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(const byte of bytes)binary+=String.fromCharCode(byte);await api.materials.import(courseId,file.name,btoa(binary));count++;}catch{failed.push(file);}}setFiles(failed);setNotice(`${count} files queued. ${failed.length} failed and remain selected for retry. Use Extract text below.`);});}
 const active=sources.filter(s=>!s.trashedAt&&!s.deletedAt&&s.cleanupState==='none');
 const displayed=trash?sources.filter(s=>s.trashedAt||s.deletedAt||s.cleanupState!=='none'):active;
 const dirty=detail?edit!==(detail.revisions[0]?.text??''):false;
 const previewable=detail&&/\.(pdf|png|jpe?g)$/i.test(detail.material.filename);
 return <section className="materials-workspace">
  <div className="page-heading"><div><p className="eyebrow">Your material</p><h1>Sources</h1><p>Preserve originals. Review the text. Prepare approved material for local search.</p></div><button disabled={busy} onClick={()=>void run(refresh)}>Refresh</button></div>
  {notice&&<p className="notice" role="status">{notice}</p>}
  <div className="course-grid">
   <section className="glass glass-card"><h2>Import files</h2><p>Text, Markdown, PDF, DOCX, DRM-free EPUB, PNG and JPEG. Up to 25 MiB each. Originals remain unchanged.</p><label>Choose files<input type="file" multiple accept=".txt,.md,.pdf,.docx,.epub,.png,.jpg,.jpeg" disabled={busy} onChange={e=>setFiles(Array.from(e.target.files??[]))}/></label><ul>{files.map((f,i)=><li key={`${f.name}:${i}`}>{f.name} · {Math.ceil(f.size/1024)} KiB</li>)}</ul><button disabled={busy||!files.length} onClick={()=>void submitFiles()}>Import selected files</button></section>
   <section className="glass glass-card"><h2>Paste text or write a note</h2><form className="form-stack" onSubmit={e=>{e.preventDefault();void run(async()=>{await api.materials.import(courseId,`${title.trim()||'Note'}.txt`,btoa(unescape(encodeURIComponent(text))),'note');changeNote('','');notes.delete(courseId);},'Note saved. Choose Extract text below to prepare it for review.');}}><label>Title<input maxLength={180} value={title} disabled={busy} onChange={e=>changeNote(e.target.value,text)}/></label><label>Your text<textarea value={text} disabled={busy} onChange={e=>changeNote(title,e.target.value)} required/></label><button disabled={busy||!text.trim()}>Save note</button></form></section>
  </div>
  <section className="glass glass-card"><h2>Local index</h2><p>Only reviewed, approved revisions are indexed. Everything runs on this Mac. Corrections and deletions make the index stale until you rebuild it.</p><p role="status">Status: {index?.index?.status??'not prepared'} · {index?.modelReady?'Local model verified':'Model unavailable'}</p>{index?.index?.rebuildReason&&index.index.status!=='building'&&<p>Reason: {index.index.rebuildReason}</p>}<button disabled={busy||!index?.modelReady||index?.index?.status==='building'} onClick={()=>void run(()=>api.materials.rebuild(courseId),'Local index build started. Status refreshes automatically.')}>Build / rebuild local index</button>{index?.index?.status==='building'&&<button disabled={busy} onClick={()=>void run(()=>api.materials.cancelIndex(courseId),'Build cancelled; you can rebuild later.')}>Cancel index build</button>}</section>
  <h2>Saved sources</h2><label><input type="checkbox" checked={trash} onChange={e=>{setTrash(e.target.checked);setSelected([]);}}/> Show trash and incomplete deletions</label>
  {trash&&<p>Trash is retained locally until you restore it or permanently delete it. Trashed content is excluded from the index. Separate exports and backups remain.</p>}
  {!trash&&<button disabled={busy||!selected.length} onClick={()=>void run(async()=>download(await api.materials.export(courseId,selected),'collegenotes-materials.json'),'Export prepared. Check your Downloads folder.')}>Export selected ({selected.length})</button>}
  <ul className="material-list">{displayed.map(s=><li key={s.id}>
   {!trash&&<input type="checkbox" aria-label={`Select ${s.filename}`} checked={selected.includes(s.id)} onChange={e=>setSelected(ids=>e.target.checked?[...ids,s.id]:ids.filter(id=>id!==s.id))}/>}
   {!trash?<button disabled={busy} onClick={()=>void openSource(s.id)}>{s.filename}</button>:<strong>{s.filename}</strong>}
   <span> Revision {s.revision} · {s.approvedRevision===s.revision?'approved':'review required'} {s.deletedAt?'· deletion incomplete':''}</span>
   {!trash?<button disabled={busy} onClick={()=>void run(async()=>{if(corrections.has(`${courseId}:${s.id}`)&&!window.confirm('Move this source to trash and discard its unsaved correction?'))return;await api.materials.trash(courseId,s.id);corrections.delete(`${courseId}:${s.id}`);if(detail?.material.id===s.id)setDetail(null);},'Moved to trash. Restore it here whenever needed.')}>Move to trash</button>:!s.deletedAt&&<button disabled={busy} onClick={()=>void run(()=>api.materials.restore(courseId,s.id),'Source restored. Rebuild the index to include approved text.')}>Restore</button>}
   <button disabled={busy} onClick={()=>{setDeleting(s);setConfirmation('');setAck(false);}}>Permanently delete</button>
  </li>)}</ul>{!displayed.length&&<p>No sources in this collection.</p>}
  {deleting&&<section className="glass glass-card" aria-labelledby="delete-material-title"><h2 id="delete-material-title">Permanently delete {deleting.filename}</h2><p>This removes the original, revisions and derived index content. It cannot be undone. Separate backups and exports remain.</p><label>Type the exact filename<input value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></label><label><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/> I understand that separate backups remain.</label><button disabled={busy||confirmation!==deleting.filename||!ack} onClick={()=>void run(async()=>{await api.materials.delete(courseId,deleting.id,confirmation,ack);corrections.delete(`${courseId}:${deleting.id}`);if(detail?.material.id===deleting.id)setDetail(null);setDeleting(null);},'Material permanently deleted.')}>Confirm permanent deletion</button><button disabled={busy} onClick={()=>setDeleting(null)}>Cancel</button></section>}
  {detail&&<section className="glass glass-card"><h2>{detail.material.filename}</h2><a className="button" href={api.materials.original(courseId,detail.material.id)}>Download unchanged original</a><button disabled={busy} onClick={()=>void run(async()=>download(await api.materials.export(courseId,[detail.material.id]),'collegenotes-material.json'),'Export prepared.')}>Export item with history</button>
   <div className="material-review-grid"><section><h3>{previewable?'Original source':'Initial extraction — compare with the downloaded original'}</h3>{previewable?<><label>Page<input type="number" min={1} max={250} value={page} onChange={e=>{setPage(Math.min(250,Math.max(1,Number(e.target.value)||1)));setPreviewError(false);}}/></label>{previewError?<p role="alert">Preview unavailable for this page. Download the original to inspect it.</p>:<img className="material-original" src={api.materials.preview(courseId,detail.material.id,page)} alt={`Unaltered original preview, page ${page}`} onError={()=>setPreviewError(true)}/>}</>:<pre className="material-text">{detail.revisions.at(-1)?.text??'Extraction has not finished.'}</pre>}</section>
   <section><h3>{detail.material.kind==='note'?'Edit your note':'Correct extracted text'}</h3><p>Check names, numbers, formulas and OCR against your original. Source anchors remain references to the original; corrected text uses its own revision offsets.</p><label>Revision text<textarea className="material-editor" disabled={busy||!detail.revisions.length} value={edit} onChange={e=>{setEdit(e.target.value);setReviewed(false);corrections.set(`${courseId}:${detail.material.id}`,{text:e.target.value,revision:expected});}}/></label>
    {expected!==detail.material.revision&&<button disabled={busy} onClick={()=>{if(window.confirm('Use your preserved draft as a correction of the latest revision? Compare the history first.')){setExpected(detail.material.revision);corrections.set(`${courseId}:${detail.material.id}`,{text:edit,revision:detail.material.revision});setReviewed(false);}}}>Use draft against latest revision</button>}
    <button disabled={busy||expected!==detail.material.revision||!dirty||!edit.trim()} onClick={()=>void run(async()=>{const d=await api.materials.correct(courseId,detail.material.id,edit,expected);corrections.delete(`${courseId}:${detail.material.id}`);setDetail(d);setExpected(d.material.revision);setReviewed(false);},'New revision saved. Review and approve it before rebuilding the index.')}>Save new revision</button>
    {corrections.has(`${courseId}:${detail.material.id}`)&&<button disabled={busy} onClick={()=>{if(window.confirm('Discard this unsaved correction?')){corrections.delete(`${courseId}:${detail.material.id}`);setEdit(detail.revisions[0]?.text??'');setExpected(detail.material.revision);setReviewed(false);}}}>Discard unsaved correction</button>}
    <label><input type="checkbox" checked={reviewed} disabled={dirty||busy||!detail.revisions.length} onChange={e=>setReviewed(e.target.checked)}/> I reviewed this saved revision against the original.</label>
    <button disabled={busy||dirty||!reviewed||!detail.revisions.length} onClick={()=>void run(async()=>{setDetail(await api.materials.approve(courseId,detail.material.id,detail.material.revision));setReviewed(false);},'Revision approved. Rebuild the local index to include it.')}>Approve saved revision</button>
   </section></div>
   <details><summary>Revision history and original source anchors</summary>{detail.revisions.map(r=><article key={r.revision}><h3>Revision {r.revision} · {r.author} · {r.createdAt}</h3><pre className="material-text">{r.text}</pre><p>Original source references (not a guarantee of corrected-text alignment):</p><pre className="material-text">{r.anchors}</pre></article>)}</details>
  </section>}
  <h2>Import queue</h2>{!tasks.length?<p>No imports yet.</p>:<ul>{tasks.map(t=><li key={t.id}><strong>{sources.find(s=>s.id===t.sourceId)?.filename??t.sourceId}</strong> · {t.status} · {t.progress}% {t.error&&<span>· {t.error}</span>}{t.status==='queued'&&<button disabled={busy} onClick={()=>void run(()=>api.materials.action(courseId,t.id,'process'))}>Extract text</button>}{['queued','running'].includes(t.status)?<button disabled={busy} onClick={()=>void run(()=>api.materials.action(courseId,t.id,'cancel'))}>Cancel extraction</button>:['failed','cancelled'].includes(t.status)&&<button disabled={busy} onClick={()=>void run(()=>api.materials.action(courseId,t.id,'retry'))}>Retry extraction</button>}</li>)}</ul>}
 </section>;
}
