import {useEffect,useState} from 'react';
import {ReadingControls,useReadingPreferences} from './ReadingControls';
import {EpubFrame} from './EpubFrame';
import {readingMatches} from '@collegenotes/domain';
import {api,type MaterialSummary,type SearchHit} from './client';
import {cachedCourses,savePack,removePack,prepareShell,packMatches,type OfflinePack} from './offline-cache';
export function OfflinePreparation({courseId,sources,onJump}:{courseId:string;sources:MaterialSummary[];onJump:(id:string,revision:number,start:number)=>void}){
 const [selected,setSelected]=useState<string[]>([]),[status,setStatus]=useState('Not prepared in this browser.'),[busy,setBusy]=useState(false),[query,setQuery]=useState(''),[hits,setHits]=useState<SearchHit[]>([]);
 useEffect(()=>{let active=true;void cachedCourses().then(async packs=>{const p=packs.find(p=>p.course.id===courseId);if(!p)return;if(!packMatches(p,sources)){await removePack(courseId);if(active)setStatus('Saved copy removed because a source changed or became unavailable. Prepare again.');}else {const local=await api.materials.index(courseId);if(active)setStatus(local.modelReady&&local.index?.status==='ready'&&local.model.version===p.index.model.version&&local.model.id===p.index.model.id?`Prepared ${p.preparedAt}. Local service provides inference and saving; browser-only copies are read-only.`:'Saved text is available, but semantic readiness is stale, missing or has a model/index mismatch. Rebuild the local index and prepare again.');}}).catch(()=>{if(active)setStatus('Browser storage unavailable. Local-service reading still works.');});return()=>{active=false;};},[courseId,sources]);
 async function prepare(){setBusy(true);try{await prepareShell();const pack=await api.offlinePack(courseId,selected);await savePack(pack);const persistent=await navigator.storage?.persist?.();setStatus(`Prepared ${pack.documents.length} readings, ${pack.activities.length} study activities, ${pack.narrations.length} narrations and ${pack.visuals.length} visual explanations. The local embedding model is verified on this Mac; fresh semantic search requires the local service. ${persistent?'Browser storage persistence granted.':'Browser may evict saved copies under storage pressure.'} Saved ${pack.preparedAt}.`);}catch(e){setStatus(`Preparation failed: ${e instanceof Error?e.message:'storage unavailable'}`);}finally{setBusy(false);}}
 async function search(kind:'lexical'|'semantic'|'hybrid'){setBusy(true);setHits([]);try{if(kind==='hybrid'){const ctx=await api.tutor.context(courseId,query);setHits(ctx.passages);setStatus(ctx.gap?ctx.gap.message:`Hybrid retrieval returned ${ctx.passages.length} passages (${ctx.requirements.length} requirements / ${ctx.explanations.length} explanations). Imported text remains data.`);}else{setHits(await api[kind](courseId,query));setStatus(`${kind==='semantic'?'Local semantic':'Lexical'} search finished. No course content left this Mac.`);}}catch(e){setStatus(`Search unavailable: ${e instanceof Error?e.message:'local service stopped'}. Approve material and rebuild the matching local index in Sources.`);}finally{setBusy(false);}}
 return <details className="glass glass-card"><summary>Course search and offline preparation</summary><p>Local service available. Reading, saving, lexical search and prepared local semantic search work without internet. Cloud providers are not connected.</p><label>Search approved course material<input value={query} maxLength={240} onChange={e=>setQuery(e.target.value)}/></label><button disabled={busy||!query.trim()} onClick={()=>void search('lexical')}>Lexical search</button><button disabled={busy||!query.trim()} onClick={()=>void search('semantic')}>Local semantic search</button><button disabled={busy||!query.trim()} onClick={()=>void search('hybrid')}>Hybrid tutor context</button><ul>{hits.map((h,i)=><li key={i}><button onClick={()=>onJump(h.sourceId,h.revision,h.start)}>{h.text}</button></li>)}</ul>
 <p>Prepare selected approved sources after building the local index. This stores an additional private copy in this browser. Separate saved copies must be removed here; other browsers and exported backups remain separate.</p>{sources.map(s=><label key={s.id}><input type="checkbox" disabled={busy||s.approvedRevision!==s.revision} checked={selected.includes(s.id)} onChange={e=>setSelected(ids=>e.target.checked?[...ids,s.id]:ids.filter(id=>id!==s.id))}/>{s.filename}{s.approvedRevision!==s.revision?' — approval required':''}</label>)}
 <button disabled={busy||!selected.length} onClick={()=>void prepare()}>Prepare selected sources offline</button><button disabled={busy} onClick={()=>void removePack(courseId).then(()=>setStatus('Browser copy removed. Local originals remain.')).catch(()=>setStatus('Could not remove browser copy. Retry.'))}>Remove browser copy</button><p role="status">{status}</p></details>;
}
export function OfflineLibrary(){
 const controls=useReadingPreferences();
 const [original,setOriginal]=useState(false),[chapter,setChapter]=useState(0);
 const [packs,setPacks]=useState<OfflinePack[]>([]),[chosen,setChosen]=useState(''),[source,setSource]=useState(''),[ordinal,setOrdinal]=useState(0),[query,setQuery]=useState(''),[notice,setNotice]=useState(''),[url,setUrl]=useState('');
 const pack=packs.find(p=>p.course.id===chosen),entry=pack?.documents.find(e=>e.document.sourceId===source),doc=entry?.document,location=doc?.locations[ordinal];
 useEffect(()=>{void cachedCourses().then(setPacks).catch(()=>setNotice('Saved browser content is unavailable. Restart the local service.'));},[]);
 useEffect(()=>{if(!entry){setUrl('');return;}const bytes=Uint8Array.from(atob(entry.originalBase64),c=>c.charCodeAt(0));const u=URL.createObjectURL(new Blob([bytes],{type:/\.pdf$/i.test(entry.document.filename)?'application/pdf':/\.png$/i.test(entry.document.filename)?'image/png':/\.jpe?g$/i.test(entry.document.filename)?'image/jpeg':'application/octet-stream'}));setUrl(u);return()=>URL.revokeObjectURL(u);},[entry]);
 async function reconnect(){try{const active=await api.courses.list();for(const p of packs){const c=active.find(c=>c.id===p.course.id);if(!c||!packMatches(p,await api.materials.list(p.course.id)))await removePack(p.course.id);}window.location.reload();}catch{setNotice('Local service is still unavailable. Start it and retry.');}}
 return <main className="glass glass-card reader-workspace" data-density={controls.preferences.density} data-reduce-motion={controls.preferences.reduceMotion}><h1>Prepared offline library</h1><p role="status">Local service unavailable. These read-only browser copies may be outdated. Local semantic inference, annotation saving and cloud features are unavailable. Lexical search of saved text works here.</p><ReadingControls {...controls}/><button onClick={()=>void reconnect()}>Reconnect to local service</button><p>{notice}</p><label>Prepared course<select value={chosen} onChange={e=>{setChosen(e.target.value);setSource('');setOrdinal(0);}}><option value="">Choose a prepared course</option>{packs.map(p=><option key={p.course.id} value={p.course.id}>{p.course.name} — {p.preparedAt}</option>)}</select></label>{!packs.length&&<p>No prepared content is available in this browser. Reconnect to the local service.</p>}
 {pack&&<><p>Snapshot {pack.preparedAt}. {pack.manifest.resources.length} checked resources. Index model: {pack.index.model.id} · {pack.index.model.version}. Model execution requires the local service; fresh generative tutoring is unavailable offline.</p><button onClick={()=>void removePack(pack.course.id).then(()=>{setPacks(p=>p.filter(x=>x.course.id!==pack.course.id));setChosen('');})}>Remove this saved course copy</button><label>Source<select value={source} onChange={e=>{setSource(e.target.value);const saved=pack?.documents.find(d=>d.document.sourceId===e.target.value);setOrdinal(saved?.document.locations.find(l=>l.start<=(saved.position?.offset??0)&&l.end>(saved.position?.offset??0))?.ordinal??0);setChapter(saved?.position?.chapter??0);}}><option value="">Choose saved source</option>{pack.documents.map(e=><option key={e.document.sourceId} value={e.document.sourceId}>{e.document.filename}</option>)}</select></label><label>Lexical search saved course<input value={query} maxLength={240} onChange={e=>setQuery(e.target.value)}/></label><ul>{pack.documents.flatMap(e=>readingMatches(e.document.text,query,20).map(m=><li key={`${e.document.sourceId}:${m.start}`}><button onClick={()=>{setSource(e.document.sourceId);setOrdinal(e.document.locations.find(l=>l.start<=m.start&&l.end>m.start)?.ordinal??0);}}>{e.document.filename}: {e.document.text.slice(m.start,m.end+60)}</button></li>))}</ul><h2>Prepared study review</h2>{pack.activities.length?<ul>{pack.activities.map(a=><li key={a.id}><strong>{a.title}</strong><p>{a.prompt}</p><small>{a.sources.length} saved source link(s) · read-only while the service is unavailable</small></li>)}</ul>:<p>No activities were prepared from the selected sources.</p>}<h2>Prepared narration</h2>{pack.narrations.length?<ul>{pack.narrations.map(n=><li key={n.asset.id}><span>{n.asset.voiceId}</span><audio controls src={`data:audio/wav;base64,${n.audioBase64}`}/></li>)}</ul>:<p>No matching narration was prepared.</p>}<h2>Prepared visual explanations</h2>{pack.visuals.length?<ul>{pack.visuals.map(v=><li key={v.id}><strong>{v.title}</strong><p>{v.state.explanation.body}</p></li>)}</ul>:<p>No visual explanations were prepared.</p>}</>}
 {doc&&entry&&<><h2>{doc.filename} · revision {doc.revision}</h2><p>{doc.warnings.join(' ')}</p><a href={url} download={doc.filename}>Save prepared unchanged original</a><label>Passage<select value={ordinal} onChange={e=>setOrdinal(Number(e.target.value))}>{doc.locations.map(l=><option key={l.ordinal} value={l.ordinal}>{l.label} ({l.ordinal+1})</option>)}</select></label><button onClick={()=>setOriginal(v=>!v)}>Show {original?'reflowed text':'prepared original'}</button><section className="reader-content" style={{fontSize:`${controls.preferences.zoom}%`,lineHeight:controls.preferences.spacing}}>{!original?<pre className="reader-text">{location?doc.text.slice(location.start,location.end):''}</pre>:entry.epub?<><label>Chapter<select value={chapter} onChange={e=>setChapter(Number(e.target.value))}>{entry.epub.chapters.map((c,i)=><option key={c.location} value={i}>{c.title}</option>)}</select></label><p>{entry.epub.warnings.join(' ')}</p><EpubFrame html={entry.epub.chapters[chapter]?.html??''} zoom={controls.preferences.zoom}/></>:/\.pdf$/i.test(doc.filename)?<iframe title="Prepared original PDF" src={url}/>:/\.(png|jpe?g)$/i.test(doc.filename)?<img className="material-original" src={url} alt="Prepared original"/>:<p>Download this prepared original to read it in its native app.</p>}</section><h3>Saved annotations</h3>{entry.annotations.map(a=><blockquote key={a.id}>Revision {a.revision} · {a.kind}: {a.quote} — {a.note}</blockquote>)}</>}
 </main>;
}
