import {useEffect,useMemo,useRef,useState} from 'react';
import {locationAt,originalPage,readingMatches,type ReadingDocument} from '@collegenotes/domain';
import {api,type MaterialSummary} from './client';
type Epub=Awaited<ReturnType<typeof api.reading.epub>>;
export function Reader({courseId}:{courseId:string}){
 const [sources,setSources]=useState<MaterialSummary[]>([]),[doc,setDoc]=useState<ReadingDocument|null>(null),[epub,setEpub]=useState<Epub|null>(null);
 const [offset,setOffset]=useState(0),[view,setView]=useState<'reflow'|'original'>('reflow'),[zoom,setZoom]=useState(100),[query,setQuery]=useState(''),[notice,setNotice]=useState(''),[page,setPage]=useState(1),[chapter,setChapter]=useState(0),[imageError,setImageError]=useState(false);
 const sequence=useRef(0);
 useEffect(()=>{let active=true;void api.materials.list(courseId).then(s=>{if(active)setSources(s.filter(m=>!m.trashedAt&&!m.deletedAt&&m.cleanupState==='none'));}).catch(()=>setNotice('Local service unavailable. Start the service and reopen Reading.'));return()=>{active=false;sequence.current++;};},[courseId]);
 async function open(id:string){const seq=++sequence.current;setNotice('');setDoc(null);setEpub(null);try{const d=await api.reading.document(courseId,id);const e=/\.epub$/i.test(d.filename)?await api.reading.epub(courseId,id):null;if(seq!==sequence.current)return;setDoc(d);setEpub(e);setOffset(0);setPage(1);setChapter(0);setImageError(false);}catch(e){if(seq===sequence.current)setNotice(`Cannot open source: ${e instanceof Error?e.message:'local service unavailable'}. Extract the text in Sources first.`);}}
 const location=doc?locationAt(doc.locations,offset):null;
 const matches=useMemo(()=>doc?readingMatches(doc.text,query):[],[doc,query]);
 function go(next:number){if(!doc)return;const l=doc.locations[Math.max(0,Math.min(doc.locations.length-1,next))];if(l){setOffset(l.start);setPage(originalPage(l)??1);const i=epub?.chapters.findIndex(c=>c.location===l.anchor?.locator.split('#')[0])??-1;if(i>=0)setChapter(i);setImageError(false);}}
 function switchView(){if(view==='reflow'){setPage(originalPage(location)??page);const i=epub?.chapters.findIndex(c=>c.location===location?.anchor?.locator.split('#')[0])??-1;if(i>=0)setChapter(i);}setView(view==='reflow'?'original':'reflow');setImageError(false);}
 return <section className="reader-workspace"><div className="page-heading"><div><p className="eyebrow">Your course library</p><h1>Reading</h1></div><a href={`#/courses/${courseId}/sources`}>Manage sources</a></div>
 <label>Source<select value={doc?.sourceId??''} onChange={e=>void open(e.target.value)}><option value="" disabled>Choose a source</option>{sources.map(s=><option key={s.id} value={s.id}>{s.filename}</option>)}</select></label>
 {notice&&<p role="status">{notice}</p>}{!sources.length&&<p>No readable sources available. Import and extract material in Sources.</p>}
 {doc&&<><p>Revision {doc.revision} · {view==='reflow'?'Reflowed extraction':'Original source rendition'}</p>{doc.warnings.map(w=><p className="notice" key={w}>{w}</p>)}
 <div className="reader-toolbar"><button onClick={switchView}>Switch to {view==='reflow'?'original':'reflowed text'}</button><a href={api.materials.original(courseId,doc.sourceId)}>Download unchanged original</a><label>Zoom<select value={zoom} onChange={e=>setZoom(Number(e.target.value))}>{[75,100,125,150,175,200].map(n=><option key={n} value={n}>{n}%</option>)}</select></label></div>
 <div className="reader-grid"><aside className="glass glass-card"><h2>Locations and headings</h2><label>Passage<select value={location?.ordinal??0} onChange={e=>go(Number(e.target.value))}>{doc.locations.map(l=><option key={l.ordinal} value={l.ordinal}>{l.ordinal+1}. {l.label} — {doc.text.slice(l.start,l.start+65).replace(/\s+/g,' ')}</option>)}</select></label><label>Find in this source<input maxLength={240} value={query} onChange={e=>setQuery(e.target.value)}/></label>{query&&<p>{matches.length}{matches.length===100?'+':''} matches</p>}<ul>{matches.map(m=><li key={m.start}><button onClick={()=>{setView('reflow');setOffset(m.start);}}>{doc.text.slice(Math.max(0,m.start-20),m.end+35)}</button></li>)}</ul></aside>
 <article className="glass glass-card reader-content" style={{fontSize:`${zoom}%`}} aria-label="Reading passage" tabIndex={0}>
 {view==='reflow'?<><h2>{location?.label??'Empty source'}</h2><pre className="reader-text">{location?doc.text.slice(location.start,location.end):''}</pre></>:epub?<><p>{epub.warnings.join(' ')}</p><label>Chapter<select value={chapter} onChange={e=>{const i=Number(e.target.value);setChapter(i);const l=doc.locations.find(l=>l.anchor?.locator.startsWith(`${epub.chapters[i]?.location}#`));if(l)setOffset(l.start);}}>{epub.chapters.map((c,i)=><option key={c.location} value={i}>{c.title}</option>)}</select></label><iframe title="Safe original EPUB chapter" sandbox="" srcDoc={`<!doctype html><meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src data:; style-src 'unsafe-inline'"><style>body{font: ${zoom}%/1.7 system-ui;padding:1rem;color:#171717;background:#fff}img{max-width:100%}table{border-collapse:collapse}td,th{border:1px solid;padding:.4rem}</style>${epub.chapters[chapter]?.html??''}`}/></>:/\.(pdf|png|jpe?g)$/i.test(doc.filename)?<><label>Original page<input type="number" min={1} max={250} value={page} onChange={e=>{const n=Math.min(250,Math.max(1,Number(e.target.value)||1));setPage(n);setImageError(false);const l=doc.locations.find(l=>originalPage(l)===n);if(l)setOffset(l.start);}}/></label>{imageError?<p role="alert">This page is unavailable. Select another page or download the original.</p>:<img className="material-original" style={{width:`${zoom}%`,maxWidth:'none'}} src={api.materials.preview(courseId,doc.sourceId,page)} alt={`Original page ${page}`} onError={()=>setImageError(true)}/>}</>:<p>This format has no embedded original viewer. Download the unchanged file above; reflowed text is available here.</p>}
 </article></div><div className="reader-toolbar"><button disabled={!location||location.ordinal===0} onClick={()=>go((location?.ordinal??0)-1)}>Previous passage</button><span>Passage {(location?.ordinal??0)+1} of {doc.locations.length}</span><button disabled={!location||location.ordinal>=doc.locations.length-1} onClick={()=>go((location?.ordinal??0)+1)}>Next passage</button></div></>}
 </section>;
}
