import {useEffect,useLayoutEffect,useMemo,useRef,useState} from 'react';
import {readingHeadings,highlightedParts,type Annotation,initialReadingPosition,locationAt,originalPage,readingMatches,type ReadingPosition,type ReadingDocument} from '@collegenotes/domain';
import {api,type MaterialSummary} from './client';
import {EpubFrame} from './EpubFrame';
import {ReadingControls,useReadingPreferences} from './ReadingControls';
import {OfflinePreparation} from './OfflineReading';
import {ReadingAnnotations} from './ReadingAnnotations';
import {pendingPosition,rememberPosition,flushPosition,resetPositionVersion} from './reading-session';
type Epub=Awaited<ReturnType<typeof api.reading.epub>>;
export function Reader({courseId}:{courseId:string}){
 const controls=useReadingPreferences(),zoom=controls.preferences.zoom;
 const [loaded,setLoaded]=useState(false);
 const [sources,setSources]=useState<MaterialSummary[]>([]),[doc,setDoc]=useState<ReadingDocument|null>(null),[epub,setEpub]=useState<Epub|null>(null);
 const [offset,setOffset]=useState(0),[view,setView]=useState<'reflow'|'original'>('reflow'),[query,setQuery]=useState(''),[notice,setNotice]=useState(''),[page,setPage]=useState(1),[chapter,setChapter]=useState(0),[imageError,setImageError]=useState(false);
 const [annotations,setAnnotations]=useState<Annotation[]>([]);
 const sequence=useRef(0),textRef=useRef<HTMLPreElement>(null),contentRef=useRef<HTMLElement>(null);
 const [position,setPosition]=useState<ReadingPosition>(initialReadingPosition(1));
 function change(patch:Partial<ReadingPosition>){if(!doc)return;setPosition(p=>{const next={...p,...patch};rememberPosition(courseId,doc.sourceId,next);return next;});}
 useEffect(()=>{if(!doc)return;const timer=setTimeout(()=>void flushPosition(courseId,doc.sourceId,doc.revision).catch(e=>setNotice(`Reading position/draft not saved: ${e.message}. Retry saving; another tab may have changed it.`)),300);return()=>clearTimeout(timer);},[courseId,doc,position]);
 useEffect(()=>{if(!doc)return;const id=doc.sourceId;const warn=(e:BeforeUnloadEvent)=>{if(pendingPosition(courseId,id,doc.revision)){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>{window.removeEventListener('beforeunload',warn);void flushPosition(courseId,id,doc.revision).catch(()=>undefined);};},[courseId,doc]);
 useEffect(()=>{if(contentRef.current)contentRef.current.scrollTop=position.scrollTop;},[doc,view]);
 function selection(){const selection=window.getSelection(),el=textRef.current;if(!doc||!location||!selection?.rangeCount||!el)return;const r=selection.getRangeAt(0);if(!el.contains(r.startContainer)||!el.contains(r.endContainer))return;const prefix=r.cloneRange();prefix.selectNodeContents(el);prefix.setEnd(r.startContainer,r.startOffset);const start=location.start+prefix.toString().length;change({selectionStart:start,selectionEnd:start+r.toString().length});}

 useEffect(()=>{let active=true;void api.materials.list(courseId).then(s=>{if(active){setSources(s.filter(m=>!m.trashedAt&&!m.deletedAt&&m.cleanupState==='none'));setLoaded(true);void api.reading.lastSource(courseId).then(last=>{if(active&&last&&s.some(m=>m.id===last.sourceId&&!m.trashedAt&&!m.deletedAt))void open(last.sourceId,last.revision);}).catch(()=>undefined);}}).catch(()=>setNotice('Local service unavailable. Start the service and reopen Reading.'));return()=>{active=false;sequence.current++;};},[courseId]);
 async function open(id:string,revision?:number,jump?:number){const seq=++sequence.current;setNotice('');try{
 if(doc)await flushPosition(courseId,doc.sourceId,doc.revision);
 const stored=await api.reading.position(courseId,id,revision);
 const saved=pendingPosition(courseId,id,revision??stored?.revision??sources.find(s=>s.id===id)?.revision??1)??stored;
 const d=await api.reading.document(courseId,id,revision??saved?.revision);const e=/\.epub$/i.test(d.filename)?await api.reading.epub(courseId,id):null;if(seq!==sequence.current)return;
 const p=saved&&saved.revision===d.revision?{...saved}:{...initialReadingPosition(d.revision),version:saved?.version??0};if(jump!==undefined){p.offset=jump;p.selectionStart=jump;p.selectionEnd=jump;p.scrollTop=0;p.frameScrollTop=0;p.view='reflow';}
 resetPositionVersion(courseId,id,p);rememberPosition(courseId,id,p);setPosition(p);setAnnotations([]);setDoc(d);setEpub(e);setOffset(p.offset);setView(p.view);setPage(p.page);setChapter(p.chapter);setImageError(false);
 if(revision!==undefined||saved)setNotice('Restored the saved source revision and exact text offset. Use Latest revision to read a newer correction.');
 }catch(e){if(seq===sequence.current)setNotice(`Cannot open source: ${e instanceof Error?e.message:'local service unavailable'}. Unsaved work is retained.`);}}

 useEffect(()=>{if(!doc)return;let active=true;const timer=setInterval(()=>void api.materials.list(courseId).then(list=>{if(!active)return;const current=list.find(s=>s.id===doc.sourceId&&!s.trashedAt&&!s.deletedAt&&s.cleanupState==='none');setSources(list.filter(s=>!s.trashedAt&&!s.deletedAt&&s.cleanupState==='none'));if(!current){setDoc(null);setNotice('This source is no longer available. Its saved copy will be removed during reconciliation.');}else if(current.revision!==doc.revision)setNotice('A newer source revision exists. Your annotations and draft stay attached to the displayed revision.');}).catch(()=>{if(active)setNotice('Local service unavailable. Unsaved work stays in this window; reload to open prepared read-only copies after saving or copying your draft.');}),10000);return()=>{active=false;clearInterval(timer);};},[courseId,doc]);
 const location=doc?locationAt(doc.locations,offset):null;
 useLayoutEffect(()=>{if(view==='reflow'&&position.scrollTop===0&&offset>0)contentRef.current?.querySelector<HTMLElement>('[data-reading-current]')?.scrollIntoView({block:'nearest',behavior:'instant'});},[doc,offset,view]);
 const headings=useMemo(()=>doc?readingHeadings(doc.text):[],[doc]);
 const matches=useMemo(()=>doc?readingMatches(doc.text,query):[],[doc,query]);
 function go(next:number){if(!doc)return;const l=doc.locations[Math.max(0,Math.min(doc.locations.length-1,next))];if(l){setOffset(l.start);setPage(originalPage(l)??1);change({offset:l.start,scrollTop:0,page:originalPage(l)??1,selectionStart:l.start,selectionEnd:l.end});if(contentRef.current)contentRef.current.scrollTop=0;const i=epub?.chapters.findIndex(c=>c.location===l.anchor?.locator.split('#')[0])??-1;if(i>=0){setChapter(i);change({chapter:i});}setImageError(false);}}
 function switchView(){if(view==='reflow'){setPage(originalPage(location)??page);const i=epub?.chapters.findIndex(c=>c.location===location?.anchor?.locator.split('#')[0])??-1;if(i>=0){setChapter(i);change({chapter:i});}}const next=view==='reflow'?'original':'reflow';setView(next);change({view:next,offset, page:originalPage(location)??page});setImageError(false);}
 return <section className="reader-workspace" data-density={controls.preferences.density} data-focus={controls.preferences.focus} data-context={controls.preferences.context} data-reduce-motion={controls.preferences.reduceMotion}><div className="page-heading"><div><p className="eyebrow">Your course library</p><h1>Reading</h1></div><a href={`#/courses/${courseId}/sources`}>Manage sources</a></div>
 <ReadingControls {...controls}/>
 {loaded&&<OfflinePreparation courseId={courseId} sources={sources} onJump={(id,revision,start)=>void open(id,revision,start)}/>}
 <label>Source<select value={doc?.sourceId??''} onChange={e=>void open(e.target.value)}><option value="" disabled>Choose a source</option>{sources.map(s=><option key={s.id} value={s.id}>{s.filename}</option>)}</select></label>
 {notice&&<p role="status">{notice}</p>}{!sources.length&&<p>No readable sources available. Import and extract material in Sources.</p>}
 {doc&&<><button onClick={()=>void open(doc.sourceId,sources.find(s=>s.id===doc.sourceId)?.revision)}>Latest revision</button><button onClick={()=>void flushPosition(courseId,doc.sourceId,doc.revision).then(()=>setNotice('Reading position and draft saved.')).catch(e=>setNotice(e.message))}>Save position and draft now</button><p>Revision {doc.revision} · {view==='reflow'?'Reflowed extraction':'Original source rendition'}</p>{doc.warnings.map(w=><p className="notice" key={w}>{w}</p>)}
 <div className="reader-toolbar"><button onClick={switchView}>Switch to {view==='reflow'?'original':'reflowed text'}</button><a href={api.materials.original(courseId,doc.sourceId)}>Download unchanged original</a></div>
 <div className="reader-grid"><aside className="glass glass-card"><h2>Locations and headings</h2>{headings.length>0&&<ul>{headings.map(h=><li key={h.start}><button onClick={()=>{setOffset(h.start);setView('reflow');change({offset:h.start,view:'reflow',scrollTop:0});}}>{h.title}</button></li>)}</ul>}<label>Passage<select value={location?.ordinal??0} onChange={e=>go(Number(e.target.value))}>{doc.locations.map(l=><option key={l.ordinal} value={l.ordinal}>{l.ordinal+1}. {l.label} — {doc.text.slice(l.start,l.start+65).replace(/\s+/g,' ')}</option>)}</select></label><label>Find in this source<input maxLength={240} value={query} onChange={e=>setQuery(e.target.value)}/></label>{query&&<p>{matches.length}{matches.length===100?'+':''} matches</p>}<ul>{matches.map(m=><li key={m.start}><button onClick={()=>{setView('reflow');setOffset(m.start);if(contentRef.current)contentRef.current.scrollTop=0;change({view:'reflow',offset:m.start,selectionStart:m.start,selectionEnd:m.end,scrollTop:0});}}>{doc.text.slice(Math.max(0,m.start-20),m.end+35)}</button></li>)}</ul></aside>
 <article ref={contentRef} onScroll={e=>change({scrollTop:e.currentTarget.scrollTop})} className="glass glass-card reader-content" style={{fontSize:`${zoom}%`,lineHeight:controls.preferences.spacing}} aria-label="Reading passage" tabIndex={0}>
 {view==='reflow'?<><h2>{location?.label??'Empty source'}</h2><pre ref={textRef} onMouseUp={selection} onKeyUp={selection} className="reader-text">{location?highlightedParts(doc.text,location.start,location.end,[...annotations.filter(a=>a.sourceId===doc.sourceId&&a.revision===doc.revision&&a.kind==='highlight'),{start:offset,end:offset}]).map(p=>p.highlighted?<mark key={p.start} data-reading-current={p.start===offset?true:undefined}>{p.text}</mark>:<span key={p.start} data-reading-current={p.start===offset?true:undefined}>{p.text}</span>):''}</pre></>:epub?<><p>{epub.warnings.join(' ')}</p><label>Chapter<select value={chapter} onChange={e=>{const i=Number(e.target.value);setChapter(i);change({chapter:i,scrollTop:0,frameScrollTop:0});const l=doc.locations.find(l=>l.anchor?.locator.startsWith(`${epub.chapters[i]?.location}#`));if(l){setOffset(l.start);change({offset:l.start});}}}>{epub.chapters.map((c,i)=><option key={c.location} value={i}>{c.title}</option>)}</select></label><EpubFrame html={epub.chapters[chapter]?.html??''} zoom={zoom} spacing={controls.preferences.spacing} scrollTop={position.frameScrollTop} onScroll={frameScrollTop=>change({frameScrollTop})}/></>:/\.(pdf|png|jpe?g)$/i.test(doc.filename)?<><label>Original page<input type="number" min={1} max={250} value={page} onChange={e=>{const n=Math.min(250,Math.max(1,Number(e.target.value)||1));setPage(n);change({page:n,scrollTop:0});setImageError(false);const l=doc.locations.find(l=>originalPage(l)===n);if(l){setOffset(l.start);change({offset:l.start});}}}/></label>{imageError?<p role="alert">This page is unavailable. Select another page or download the original.</p>:<img className="material-original" style={{width:`${zoom}%`,maxWidth:'none'}} src={api.materials.preview(courseId,doc.sourceId,page)} alt={`Original page ${page}`} onLoad={()=>{if(contentRef.current)contentRef.current.scrollTop=position.scrollTop;}} onError={()=>setImageError(true)}/>}</>:<p>This format has no embedded original viewer. Download the unchanged file above; reflowed text is available here.</p>}
 </article></div><div className="reader-toolbar"><button disabled={!location||location.ordinal===0} onClick={()=>go((location?.ordinal??0)-1)}>Previous passage</button><span>Passage {(location?.ordinal??0)+1} of {doc.locations.length}</span><button disabled={!location||location.ordinal>=doc.locations.length-1} onClick={()=>go((location?.ordinal??0)+1)}>Next passage</button></div><ReadingAnnotations key={`${doc.sourceId}:${doc.revision}`} doc={doc} position={position} change={change} onJump={(revision,start)=>void open(doc.sourceId,revision,start)} onError={setNotice} onAnnotations={setAnnotations}/></>}
 </section>;
}
