import {useEffect,useState} from 'react';
import type {StudyProgress as Progress,StudyActivitySummary} from '@collegenotes/domain';
import {api} from './client';
export function StudyProgressPanel({courseId,onStart}:{courseId:string;onStart?:(id:string)=>void}) {
 const [progress,setProgress]=useState<Progress|null>(null),[activities,setActivities]=useState<StudyActivitySummary[]>([]),[notice,setNotice]=useState(''),[limit,setLimit]=useState(5),[busy,setBusy]=useState(false);
 useEffect(()=>{let active=true;void Promise.all([api.study.progress(courseId),api.study.activities(courseId)]).then(([p,a])=>{if(active){setProgress(p);setLimit(p.dailyLimit);setActivities(a);}}).catch(e=>{if(active)setNotice(e.message);});return()=>{active=false;};},[courseId]);
 async function action(work:()=>Promise<Progress>){setBusy(true);try{setProgress(await work());setNotice('Saved locally.');}catch(e){setNotice(e instanceof Error?e.message:'Could not update review queue.');}finally{setBusy(false);}}
 return <section className="glass glass-card"><h2>Review and learning history</h2><p role="status">{notice}</p>{!progress?<p>Loading progress. Enable the Study module if unavailable.</p>:<><p>{progress.explanation}</p><p>{progress.submitted} submitted attempts · {progress.correctUnaided} correct unassisted attempts on current sources · {progress.assisted} assisted attempts · {progress.needsReview} explanations needing review.</p><p>{progress.staleActivities} activities need rebuilding after a source change.</p>
 <form onSubmit={e=>{e.preventDefault();void action(()=>api.study.workload(courseId,limit));}}><label>Daily workload (1–50 activities)<input type="number" min={1} max={50} required value={limit} onChange={e=>setLimit(Number(e.target.value))}/></label><button disabled={busy}>Save workload</button></form>
 <h3>Review queue</h3><p>{progress.dueTotal} due · {progress.remainingToday} places left today (UTC).</p>{!progress.due.length&&<p>No items in today’s queue. You can still practice any prepared activity.</p>}<ul>{progress.due.map(d=><li key={d.activityId}>{d.title} · due {new Date(d.dueAt).toLocaleString()} {onStart?<button disabled={busy} onClick={()=>onStart(d.activityId)}>Study this</button>:<a href={`#/courses/${courseId}/study`}>Open Study</a>}</li>)}</ul>
 <details><summary>Reset or undo review schedules</summary><p>Reset makes an activity due now and keeps all attempts. Undo restores its previous schedule until another attempt is submitted.</p>{activities.filter(a=>a.status==='ready').map(a=><p key={a.id}>{a.title} <button disabled={busy} onClick={()=>void action(()=>api.study.review(courseId,a.id,'reset'))}>Reset schedule</button> <button disabled={busy} onClick={()=>void action(()=>api.study.review(courseId,a.id,'undo'))}>Undo reset</button></p>)}</details>
 <h3>Attempt evidence</h3><ul>{progress.history.filter(h=>h.status==='submitted').map(h=><li key={h.id}>{activities.find(a=>a.id===h.activityId)?.title} · {h.submittedAt?new Date(h.submittedAt).toLocaleString():''} · {h.feedback?.outcome.replace('_',' ')} · {h.hintCount} hints{activities.find(a=>a.id===h.activityId)?.status==='stale'?' · Source changed; excluded from current recall evidence':''}<p>Your explanation: {h.teachBack||'No teach-back recorded.'}</p></li>)}</ul></>}</section>;
}
