import { StudyAttemptPanel } from './StudyAttempt';
import { useEffect, useState } from 'react';
import { ACTIVITY_KINDS, type ActivityKind, type ActivityTemplate, type StudyActivity, type AttemptView, type StudyAttempt } from '@collegenotes/domain';
import { api, type MaterialSummary } from './client';
const labels: Record<ActivityKind,string> = {classification:'Classification',ordering:'Ordering',recall:'Short recall',multiple_choice:'Multiple choice',evidence_matching:'Evidence matching',prediction:'Prediction with explanation'};
const lines=(s:string)=>s.split('\n').map(s=>s.trim()).filter(Boolean);
export function StudyWorkspace({courseId}:{courseId:string}) {
 const [attempt,setAttempt]=useState<AttemptView|null>(null),[history,setHistory]=useState<StudyAttempt[]>([]);
 async function start(id:string){try{setAttempt(await api.study.start(courseId,id));setHistory(await api.study.attempts(courseId));}catch(e){setNotice(e instanceof Error?e.message:'Attempt unavailable.');}}
 const [activities,setActivities]=useState<StudyActivity[]>([]),[materials,setMaterials]=useState<MaterialSummary[]>([]),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const [kind,setKind]=useState<ActivityKind>('recall'),[sourceId,setSourceId]=useState(''),[title,setTitle]=useState(''),[prompt,setPrompt]=useState(''),[items,setItems]=useState(''),[choices,setChoices]=useState(''),[answer,setAnswer]=useState(''),[rationale,setRationale]=useState(''),[rubric,setRubric]=useState(''),[hints,setHints]=useState(''),[needsReview,setNeedsReview]=useState(false);
 async function refresh(){setActivities(await api.study.activities(courseId));setHistory(await api.study.attempts(courseId));}
 useEffect(()=>{let active=true;void Promise.all([api.study.activities(courseId),api.materials.list(courseId),api.study.attempts(courseId)]).then(([a,m,h])=>{if(active){setActivities(a);setHistory(h);setMaterials(m.filter(m=>m.approvedRevision===m.revision&&!m.trashedAt&&!m.deletedAt));}}).catch(e=>{if(active)setNotice(String(e.message));});return()=>{active=false;};},[courseId]);
 async function create(e:React.FormEvent){e.preventDefault();setBusy(true);try{const detail=await api.materials.detail(courseId,sourceId);const revision=detail.revisions.find(r=>r.revision===detail.material.revision);if(!revision)throw Error('Review and approve this source first.');if(revision.text.length>20000)throw Error('Use a shorter source excerpt (up to 20,000 characters) for this activity.');const template:ActivityTemplate={schemaVersion:1,kind,title,prompt,items:['classification','ordering','evidence_matching'].includes(kind)?lines(items):[],choices:['classification','multiple_choice','evidence_matching'].includes(kind)?lines(choices):[],answer:['recall','prediction','multiple_choice'].includes(kind)?[answer]:lines(answer),rationale,rubric:lines(rubric),hints:lines(hints),sources:[{sourceId,revision:revision.revision,start:0,end:revision.text.length,quote:revision.text}],provenance:{kind:'user',providerId:null,modelId:null},needsReview};await api.study.create(courseId,template);await refresh();setNotice('Activity saved locally.');}catch(e){setNotice(e instanceof Error?e.message:'Could not save activity.');}finally{setBusy(false);}}
 return <section className="glass glass-card"><h1>Study</h1><p>Prepare source-linked activities and study locally. No AI connection is needed.</p><p role="status">{notice}</p>
 <details><summary>Create an activity</summary><form className="form-stack" onSubmit={e=>void create(e)}>
 <label>Approved source<select required value={sourceId} onChange={e=>setSourceId(e.target.value)}><option value="">Choose a source</option>{materials.map(m=><option key={m.id} value={m.id}>{m.filename}</option>)}</select></label>
 <label>Activity type<select value={kind} onChange={e=>setKind(e.target.value as ActivityKind)}>{ACTIVITY_KINDS.map(k=><option key={k} value={k}>{labels[k]}</option>)}</select></label>
 <label>Title<input required maxLength={200} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Question<textarea required value={prompt} onChange={e=>setPrompt(e.target.value)}/></label>
 {['classification','ordering','evidence_matching'].includes(kind)&&<label>Items (one per line)<textarea required value={items} onChange={e=>setItems(e.target.value)}/></label>}
 {['classification','multiple_choice','evidence_matching'].includes(kind)&&<label>Choices or categories (one per line)<textarea required value={choices} onChange={e=>setChoices(e.target.value)}/></label>}
 <label>Prepared answer {['classification','evidence_matching'].includes(kind)?'(one choice per item, in item order)':kind==='ordering'?'(items in correct order, one per line)':''}<textarea required value={answer} onChange={e=>setAnswer(e.target.value)}/></label>
 <label>Answer rationale<textarea required value={rationale} onChange={e=>setRationale(e.target.value)}/></label><label>Rubric (one criterion per line)<textarea required value={rubric} onChange={e=>setRubric(e.target.value)}/></label><label>Graduated hints (up to five, one per line)<textarea value={hints} onChange={e=>setHints(e.target.value)}/></label><label><input type="checkbox" checked={needsReview} onChange={e=>setNeedsReview(e.target.checked)}/>Ambiguous answer: require review</label><button disabled={busy}>Save activity</button></form></details>
 {attempt&&<StudyAttemptPanel key={attempt.attempt.id} initial={attempt} onRetry={()=>void start(attempt.activity.id)} onSubmitted={()=>void refresh()}/>}
 <h2>Saved attempts</h2>{history.map(h=><p key={h.id}>{activities.find(a=>a.id===h.activityId)?.title} · {h.status} <button disabled={activities.find(a=>a.id===h.activityId)?.status!=='ready'} onClick={()=>void api.study.attempt(courseId,h.id).then(setAttempt).catch(e=>setNotice(e.message))}>Open attempt</button></p>)}
 <h2>Prepared activities</h2>{!activities.length&&<p>No activities yet. Import and approve a source, then create an activity.</p>}{activities.map(a=><article className="glass glass-card" key={a.id}><h3>{a.title}</h3><p>{labels[a.kind]} · {a.status==='stale'?'Source changed — recreate this activity':'Ready'} · {a.provenance.kind==='user'?'User-authored':`Model: ${a.provenance.providerId} / ${a.provenance.modelId}`}</p><p>{a.prompt}</p><button disabled={busy||a.status!=='ready'} onClick={()=>void start(a.id)}>Start attempt</button><button disabled={busy} onClick={()=>{if(window.confirm('Delete this activity and its learning records? Course sources remain.'))void api.study.remove(courseId,a.id).then(refresh).catch(e=>setNotice(e.message));}}>Delete activity</button></article>)}</section>;
}
