import {useEffect,useState} from 'react';
import type {StudySession} from '@collegenotes/domain';
import {api} from './client';
import {StudyAttemptPanel} from './StudyAttempt';
export function StudySessionPanel({courseId,onChange}:{courseId:string;onChange:()=>void}) {
 const [session,setSession]=useState<StudySession|null>(null),[limit,setLimit]=useState(3),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[saving,setSaving]=useState(false),[loaded,setLoaded]=useState(false);
 useEffect(()=>{let active=true;void api.study.session(courseId).then(s=>{if(active){setSession(s);setLoaded(true);}}).catch(e=>{if(active)setNotice(e.message);});return()=>{active=false;};},[courseId]);
 async function act(action:string){setBusy(true);try{const next=action==='start'?await api.study.openSession(courseId,limit):await api.study.changeSession(courseId,session!.id,session!.version,action);setSession(next);setNotice(next.status==='complete'?'Session complete. You can stop here.':'Saved locally.');onChange();}catch(e){setNotice(e instanceof Error?e.message:'Session unavailable.');}finally{setBusy(false);}}
 return <section className="glass glass-card"><h2>A short study session</h2><p>Prepared study works without internet while the local app service is running. Wait for “Saved locally” before closing the window.</p><p role="status">{notice}</p>{!loaded?<p>Loading saved session…</p>:!session||session.status==='complete'?<form onSubmit={e=>{e.preventDefault();void act('start');}}><label>Activities this session (1–10)<input required type="number" min={1} max={10} value={limit} onChange={e=>setLimit(Number(e.target.value))}/></label><button disabled={busy}>Start next session</button></form>:<><p>Activity {session.position+1} of {session.total} · {session.status}</p>{session.status==='paused'?<button disabled={busy} onClick={()=>void act('resume')}>Resume saved session</button>:<><button disabled={busy||saving} onClick={()=>void act('pause')}>Pause and stop here</button>{session.unavailable?<p role="status">{session.unavailable}</p>:session.current?<StudyAttemptPanel key={session.current.attempt.id} initial={session.current} onRetry={()=>void act('retry')} onPending={setSaving} onSubmitted={()=>{void api.study.session(courseId).then(setSession).catch(e=>setNotice(e.message));onChange();}}/>:null}<button disabled={busy||saving||Boolean(session.current&&session.current.attempt.status!=='submitted')} onClick={()=>void act('continue')}>Continue to next activity</button></>}</>}</section>;
}
