import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import vm from 'node:vm';import {execFileSync} from 'node:child_process';
import {afterEach,expect,it} from 'vitest';
import {openStore,createCourse,storeOriginal,approveMaterial,beginIndex,finishIndex,lexicalSearch,preparedIndex,correctMaterial,type Store} from '@collegenotes/storage';
import {createService} from '../../apps/local-service/src/index.js';import {LOCAL_MODEL} from '../../apps/local-service/src/semantic.js';
const stores:Store[]=[];afterEach(()=>{for(const s of stores.splice(0)){s.db.close();fs.rmSync(s.dataDir,{recursive:true,force:true});}});
function fixture(){const s=openStore(fs.mkdtempSync(path.join(os.tmpdir(),'cn-offline-')));stores.push(s);const c=createCourse(s,'Synthetic offline');const m=storeOriginal(s,c.id,'offline.txt',Buffer.from('Photosynthesis converts sunlight into energy.'));s.db.prepare("insert into material_revisions values (?,?,1,?,'[]','extraction',?)").run(m.id,c.id,'Photosynthesis converts sunlight into energy.',m.createdAt);approveMaterial(s,c.id,m.id,{expectedRevision:1,reviewed:true});const snapshot=beginIndex(s,c.id,LOCAL_MODEL);finishIndex(s,snapshot,snapshot.chunks.map(()=>Array.from({length:384},(_,i)=>i===0?1:0)));return {s,c,m};}
it('CHK-7.3-01 production shell cold fetch uses cached local assets when all network requests fail',async()=>{
 const code=fs.readFileSync('apps/web/dist/sw.js','utf8');const handlers=new Map<string,(e:unknown)=>void>();const cache=new Map<string,unknown>();const context={URL,self:{location:{origin:'http://127.0.0.1:4173'},clients:{claim:async()=>{}},addEventListener:(name:string,handler:(e:unknown)=>void)=>handlers.set(name,handler)},caches:{open:async()=>({addAll:async(names:string[])=>{for(const n of names){expect(fs.existsSync(`apps/web/dist${n}`)).toBe(true);cache.set(n,{cached:n});}},match:async(n:string)=>cache.get(n)}),keys:async()=>[],delete:async()=>true},fetch:()=>{throw new Error('network_denied');}};
 vm.runInNewContext(code,context);let pending:Promise<unknown>|undefined;handlers.get('install')!({waitUntil:(p:Promise<unknown>)=>{pending=p;}});await pending;let response:Promise<unknown>|undefined;handlers.get('fetch')!({request:{method:'GET',url:'http://127.0.0.1:4173/',mode:'navigate'},respondWith:(p:Promise<unknown>)=>{response=p;}});expect(await response).toEqual({cached:'/index.html'});
 response=undefined;handlers.get('fetch')!({request:{method:'GET',url:'http://127.0.0.1:4781/courses',mode:'cors'},respondWith:(p:Promise<unknown>)=>{response=p;}});expect(response).toBeUndefined();expect([...cache.keys()].some(k=>k.endsWith('.css'))).toBe(true);expect(code).not.toMatch(/https:\/\//);
});
it('CHK-7.3-02 prepared local reading, lexical/vector retrieval and annotations work in OS network denial',()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'cn-offline-denied-'));
 try{const code=`import {embedTexts} from './packages/importers/dist/embeddings.js';import {openStore,createCourse,storeOriginal,approveMaterial,beginIndex,finishIndex,readingDocument,lexicalSearch,semanticSearch,addAnnotation} from './packages/storage/dist/index.js';const s=openStore(${JSON.stringify(dir)});const c=createCourse(s,'Synthetic disconnected');const m=storeOriginal(s,c.id,'a.txt',Buffer.from('sunlight energy'));s.db.prepare("insert into material_revisions values (?,?,1,?,'[]','extraction',?)").run(m.id,c.id,'sunlight energy',m.createdAt);approveMaterial(s,c.id,m.id,{expectedRevision:1,reviewed:true});const model={id:'synthetic',version:'1',checksum:'test'},snap=beginIndex(s,c.id,model);const vectors=await embedTexts(snap.chunks.map(c=>c.text));finishIndex(s,snap,vectors);const [vector]=await embedTexts(['sunlight']);if(readingDocument(s,c.id,m.id).text!=='sunlight energy'||lexicalSearch(s,c.id,'sunlight',model).length!==1||semanticSearch(s,c.id,vector,model).length!==1)throw Error('retrieval');addAnnotation(s,c.id,m.id,{revision:1,kind:'highlight',start:0,end:8,quote:'sunlight',note:'offline'});s.db.close();console.log('offline core passed');`;
 const output=execFileSync('/usr/bin/sandbox-exec',['-p','(version 1) (allow default) (deny network*)',process.execPath,'--input-type=module','-e',code],{encoding:'utf8'});expect(output).toContain('offline core passed');}finally{fs.rmSync(dir,{recursive:true,force:true});}
});
it('CHK-7.3-03 missing, changed and mismatched index content is rejected explicitly',()=>{const {s,c,m}=fixture();expect(lexicalSearch(s,c.id,'sunlight',LOCAL_MODEL)[0]?.sourceId).toBe(m.id);expect(()=>preparedIndex(s,c.id,[m.id],{...LOCAL_MODEL,version:'different'})).toThrow('index_rebuild_required');expect(()=>preparedIndex(s,c.id,['missing'],LOCAL_MODEL)).toThrow('approve_selected_sources_and_rebuild');correctMaterial(s,c.id,m.id,{expectedRevision:1,text:'Correction'});expect(()=>lexicalSearch(s,c.id,'sunlight',LOCAL_MODEL)).toThrow('index_rebuild_required');});
it('CHK-7.3-04 preparation exports selected originals, annotations and versioned vectors without filesystem paths',async()=>{const {s,c,m}=fixture();const app=createService(s);try{const response=await app.inject({method:'POST',url:`/courses/${c.id}/offline-pack`,payload:{sourceIds:[m.id]}});expect(response.statusCode).toBe(200);const pack=response.json();expect(pack.documents).toHaveLength(1);expect(pack.index.model).toEqual(LOCAL_MODEL);expect(pack.index.chunks[0].vector).toHaveLength(384);expect(Buffer.from(pack.documents[0].originalBase64,'base64').toString()).toContain('Photosynthesis');expect(JSON.stringify(pack)).not.toContain(s.dataDir);}finally{await app.close();}});
it('CHK-7.3-05 local readiness never grants cloud availability or cross-course retrieval',async()=>{const {s,c,m}=fixture();const other=createCourse(s,'Other');const app=createService(s);try{expect((await app.inject('/connections')).json().liveAuthenticationAvailable).toBe(false);expect((await app.inject({method:'POST',url:`/courses/${other.id}/offline-pack`,payload:{sourceIds:[m.id]}})).statusCode).toBe(404);const r=await app.inject({method:'POST',url:`/courses/${c.id}/lexical-search`,payload:{query:'sunlight'}});expect(r.statusCode).toBe(200);expect(r.json()[0].sourceId).toBe(m.id);}finally{await app.close();}});
