import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import Database from 'better-sqlite3';import {afterEach,expect,it} from 'vitest';
import {openStore,createCourse,storeOriginal,correctMaterial,saveReadingPosition,readingPosition,lastReadingSource,readingDocument,addAnnotation,approveMaterial,beginIndex,finishIndex,lexicalSearch,type Store} from '@collegenotes/storage';
import {MIGRATIONS} from '../../packages/storage/src/migrations.js';
import {readingPreferences,initialReadingPosition,readingHeadings,locationAt} from '@collegenotes/domain';
const stores:Store[]=[];afterEach(()=>{for(const s of stores.splice(0)){s.db.close();fs.rmSync(s.dataDir,{recursive:true,force:true});}});
function fixture(){const s=openStore(fs.mkdtempSync(path.join(os.tmpdir(),'cn-controls-')));stores.push(s);return s;}
function source(s:Store,c:string,text='First second'){const m=storeOriginal(s,c,'test.txt',Buffer.from(text));s.db.prepare("insert into material_revisions values (?,?,1,?,'[]','extraction',?)").run(m.id,c,text,m.createdAt);return m;}
it('CHK-7.4-01 keyboard-addressable headings preserve exact source offsets',()=>{const text='# First\n\nText\n\n## Second\nmore';const headings=readingHeadings(text);expect(headings.map(h=>h.title)).toEqual(['First','Second']);expect(text.slice(headings[1]!.start,headings[1]!.end)).toBe('## Second');expect(headings[1]?.level).toBe(2);});
it('CHK-7.4-02 reading preferences survive serialization, bound zoom and preserve all control choices',()=>{const p=readingPreferences({zoom:200,density:'compact',spacing:2,focus:true,reduceMotion:true,context:false});expect(readingPreferences(JSON.parse(JSON.stringify(p)))).toEqual(p);expect(readingPreferences({zoom:-100,spacing:99,density:'fake'})).toMatchObject({zoom:100,spacing:1.7,density:'comfortable'});});
it('CHK-7.4-03 unfinished drafts and exact positions remain distinct for old and corrected revisions',()=>{const s=fixture(),c=createCourse(s,'A'),m=source(s,c.id);saveReadingPosition(s,c.id,m.id,{...initialReadingPosition(1),draft:'Old version draft',offset:3});correctMaterial(s,c.id,m.id,{expectedRevision:1,text:'New wording'});saveReadingPosition(s,c.id,m.id,{...initialReadingPosition(2),draft:'New version draft',offset:7});expect(readingPosition(s,c.id,m.id,1)?.draft).toBe('Old version draft');expect(readingPosition(s,c.id,m.id,2)?.offset).toBe(7);expect(lastReadingSource(s,c.id)).toMatchObject({sourceId:m.id,revision:2});});
it('upgrades a real version-12 database without losing saved drafts or foreign key integrity',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'cn-reader-upgrade-'));
 // Build the previous schema, seed a real saved position, then migrate through normal startup.
 const raw=new Database(path.join(dir,'collegenotes.sqlite'));raw.exec('create table schema_migrations(version integer primary key,applied_at text not null)');for(let i=0;i<12;i++){raw.exec(MIGRATIONS[i]!);raw.prepare('insert into schema_migrations values (?,?)').run(i+1,'synthetic');}const oldStore={db:raw,dataDir:dir,originalsDir:path.join(dir,'originals')};fs.mkdirSync(oldStore.originalsDir,{recursive:true});const course=createCourse(oldStore,'Synthetic migration'),m=source(oldStore,course.id);raw.prepare('insert into reading_positions values (?,?,?,?,?,?)').run(m.id,course.id,1,JSON.stringify({...initialReadingPosition(1),draft:'Preserved from version 12'}),1,'synthetic');raw.close();
 const s=openStore(dir);expect(readingPosition(s,course.id,m.id,1)?.draft).toBe('Preserved from version 12');stores.push(s);expect(s.db.prepare('select count(*) as n from schema_migrations').get()).toEqual({n:MIGRATIONS.length});expect(s.db.pragma('foreign_key_check')).toEqual([]);
});
it('CHK-7.4-04 storage responsiveness diagnostic on 3 courses, 100 documents and 10000 passages',()=>{
 const s=fixture(),courses=Array.from({length:3},(_,i)=>createCourse(s,`Synthetic performance ${i}`)),docs=[];const model={id:'synthetic',version:'1',checksum:'test'};
 for(let n=0;n<100;n++){const c=courses[n%3]!;const text=Array.from({length:100},(_,i)=>`Passage ${i}: photosynthesis captures sunlight for energy.\n\n`).join('');const m=source(s,c.id,text);let at=0;const anchors=text.split(/(?<=\n\n)/).filter(Boolean).map((part,i)=>{const a={type:'paragraph',locator:`paragraph:${i+1}`,textStart:at,textEnd:at+part.length};at+=part.length;return a;});s.db.prepare('update material_revisions set anchors=? where source_id=?').run(JSON.stringify(anchors),m.id);approveMaterial(s,c.id,m.id,{expectedRevision:1,reviewed:true});docs.push({c,m});}
 for(const c of courses){const snapshot=beginIndex(s,c.id,model);finishIndex(s,snapshot,snapshot.chunks.map(()=>Array.from({length:384},(_,i)=>i===0?1:0)));}
 const results=[];for(let run=0;run<3;run++){const samples=[];for(let n=0;n<100;n++){const {c,m}=docs[n]!,start=performance.now();switch(n%5){case 0:readingDocument(s,c.id,m.id);break;case 1:locationAt(readingDocument(s,c.id,m.id).locations,4001);break;case 2:addAnnotation(s,c.id,m.id,{revision:1,kind:'note',start:0,end:7,quote:'Passage',note:'Synthetic measurement'});break;case 3:lastReadingSource(s,c.id);break;case 4:lexicalSearch(s,c.id,'sunlight',model);break;}samples.push(performance.now()-start);}const sorted=[...samples].sort((a,b)=>a-b);results.push({run:run+1,samples,p95:sorted[Math.ceil(.95*sorted.length)-1]});}
 fs.mkdirSync('.local/phase7',{recursive:true});fs.writeFileSync('.local/phase7/reading-storage-performance.json',JSON.stringify({scope:'Storage diagnostic only; not input-to-paint P-INTERACT acceptance. No UI, browser, PDF render or 1000 learning-attempt workload.',results},null,2));expect(results.every(r=>r.p95!<200)).toBe(true);
});
