import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {afterEach,expect,it} from 'vitest';import JSZip from 'jszip';
import {openStore,createCourse,storeOriginal,readingDocument,correctMaterial,trashMaterial,type Store} from '@collegenotes/storage';
import {readingLocations,readingMatches,originalPage,locationAt,parseHash} from '@collegenotes/domain';
import {epubReading} from '@collegenotes/importers';import {createService} from '../../apps/local-service/src/index.js';
const stores:Store[]=[];afterEach(()=>{for(const s of stores.splice(0)){s.db.close();fs.rmSync(s.dataDir,{recursive:true,force:true});}});
function setup(text='First page\n\nRepeated phrase. Repeated phrase.'){const s=openStore(fs.mkdtempSync(path.join(os.tmpdir(),'cn-reading-')));stores.push(s);const c=createCourse(s,'Synthetic reading');const m=storeOriginal(s,c.id,'sample.txt',Buffer.from(text));s.db.prepare("insert into material_revisions values (?,?,1,?,?,'extraction',?)").run(m.id,c.id,text,JSON.stringify([{type:'page',locator:'page:1',textStart:0,textEnd:12},{type:'page',locator:'page:2',textStart:12,textEnd:text.length}]),m.createdAt);return {s,c,m};}
it('CHK-7.1-01 preserves exact page offsets and discloses correction alignment loss',()=>{const {s,c,m}=setup();const d=readingDocument(s,c.id,m.id);expect(d.locations.map(originalPage)).toEqual([1,2]);expect(locationAt(d.locations,13)?.start).toBe(12);correctMaterial(s,c.id,m.id,{expectedRevision:1,text:'Corrected'});expect(readingDocument(s,c.id,m.id).exactOriginalMapping).toBe(false);expect(readingDocument(s,c.id,m.id,1).text).toContain('Repeated');});
it('CHK-7.1-02 bounded passages preserve Unicode and layout characters across pagination',()=>{const text='a'.repeat(3999)+'😀\n\tTABLE\n'+ 'z'.repeat(9000);const ls=readingLocations(text,[],false);expect(ls.map(l=>text.slice(l.start,l.end)).join('')).toBe(text);expect(ls.every(l=>l.end-l.start<=4000)).toBe(true);expect(ls[0]?.end).toBe(3999);});
it('CHK-7.1-03 navigation targets and repeated search occurrences have exact offsets',()=>{expect(parseHash('#/courses/a/reading',['a']).route).toEqual({name:'reading',courseId:'a'});expect(readingMatches('İ REPEAT repeat','repeat')).toEqual([{start:2,end:8},{start:9,end:15}]);expect(readingMatches('a.b axb','a.b')).toEqual([{start:0,end:3}]);});
it('CHK-7.1-04 large documents page without dropping or duplicating source text',()=>{const text='0123456789'.repeat(200000);const ls=readingLocations(text,[],false);expect(ls).toHaveLength(500);expect(ls.map(l=>text.slice(l.start,l.end)).join('')).toBe(text);expect(readingMatches(text,'01')).toHaveLength(100);});
it('CHK-7.1-05 safe EPUB preserves table structure and blocks active/remote content',async()=>{const zip=new JSZip();zip.file('mimetype','application/epub+zip');zip.file('META-INF/container.xml','<container><rootfile full-path="book.opf"/></container>');zip.file('book.opf','<package><manifest><item id="a" href="a.xhtml"/></manifest><spine><itemref idref="a"/></spine></package>');zip.file('a.xhtml','<html><body><h1>Title</h1><script>secret()</script><table><tr><td>42</td></tr></table><img src="https://example.com/tracker" onload="evil()" alt="Figure"/></body></html>');const out=await epubReading(await zip.generateAsync({type:'nodebuffer'}));expect(out.chapters[0]?.html).toContain('<table><tr><td>42</td></tr></table>');expect(out.chapters[0]?.html).toContain('Image unavailable');expect(out.chapters[0]?.html).not.toMatch(/secret|https:|onload/);expect(out.warnings[0]).toContain('excluded');});
it('reader API rejects foreign, trashed and missing revisions',async()=>{const {s,c,m}=setup();const app=createService(s);try{expect((await app.inject(`/courses/${c.id}/reading/${m.id}`)).statusCode).toBe(200);expect((await app.inject(`/courses/${c.id}/reading/${m.id}?revision=2`)).statusCode).toBe(404);const other=createCourse(s,'Other');expect((await app.inject(`/courses/${other.id}/reading/${m.id}`)).statusCode).toBe(404);trashMaterial(s,c.id,m.id);expect((await app.inject(`/courses/${c.id}/reading/${m.id}`)).statusCode).toBe(404);}finally{await app.close();}});

import {addAnnotation,readingAnnotations,changeAnnotation,readingPosition,saveReadingPosition,exportMaterials,deleteMaterial} from '@collegenotes/storage';
import {initialReadingPosition,highlightedParts} from '@collegenotes/domain';
it('CHK-7.2-01 repeated phrases bind exact offsets and quote, not first occurrence',()=>{const {s,c,m}=setup('same same');const a=addAnnotation(s,c.id,m.id,{revision:1,kind:'highlight',start:5,end:9,quote:'same',note:''});expect(a.start).toBe(5);expect(()=>addAnnotation(s,c.id,m.id,{revision:1,kind:'note',start:0,end:4,quote:'wrong',note:''})).toThrow('invalid_annotation');expect(highlightedParts('same same',0,9,[a]).map(p=>[p.text,p.highlighted])).toEqual([['same ',false],['same',true]]);});
it('CHK-7.2-02 corrections preserve historical annotation and export its revision',()=>{const {s,c,m}=setup('same same');addAnnotation(s,c.id,m.id,{revision:1,kind:'note',start:5,end:9,quote:'same',note:'Second occurrence'});correctMaterial(s,c.id,m.id,{expectedRevision:1,text:'new wording'});expect(readingAnnotations(s,c.id,m.id)[0]?.revision).toBe(1);expect(exportMaterials(s,c.id,[m.id]).data.sources[0]?.annotations).toHaveLength(1);});
it('CHK-7.2-03 exact position, original mode and unfinished annotation survive database restart',()=>{const {s,c,m}=setup();const p={...initialReadingPosition(1),offset:15,view:'original' as const,page:2,scrollTop:123.5,draft:'unfinished',selectionStart:15,selectionEnd:17};saveReadingPosition(s,c.id,m.id,p);s.db.close();const reopened=openStore(s.dataDir);stores[stores.indexOf(s)]=reopened;expect(readingPosition(reopened,c.id,m.id)).toEqual({...p,version:1});expect(()=>saveReadingPosition(reopened,c.id,m.id,p)).toThrow('reading_position_conflict');});
it('CHK-7.2-04 keyboard range alternative rejects reversed and out of bounds selection',()=>{const {s,c,m}=setup();expect(()=>saveReadingPosition(s,c.id,m.id,{...initialReadingPosition(1),selectionStart:10,selectionEnd:3})).toThrow('invalid_reading_range');expect(()=>addAnnotation(s,c.id,m.id,{revision:1,kind:'bookmark',start:999,end:999,quote:'',note:''})).toThrow('invalid_reading_range');const a=addAnnotation(s,c.id,m.id,{revision:1,kind:'bookmark',start:3,end:3,quote:'',note:''});expect(a.start).toBe(3);});
it('CHK-7.2-05 annotations never reassign, cross courses or survive permanent source deletion',()=>{const {s,c,m}=setup();const a=addAnnotation(s,c.id,m.id,{revision:1,kind:'note',start:0,end:5,quote:'First',note:'A'});changeAnnotation(s,c.id,m.id,a.id,{version:1,note:'B'});expect(()=>changeAnnotation(s,c.id,m.id,a.id,{version:1,note:'C'})).toThrow('annotation_conflict');const other=createCourse(s,'Foreign');expect(()=>readingAnnotations(s,other.id,m.id)).toThrow('material_unavailable');saveReadingPosition(s,c.id,m.id,initialReadingPosition(1));deleteMaterial(s,c.id,m.id,{confirmation:m.filename,backupsAcknowledged:true});expect(s.db.prepare('select count(*) as n from reading_annotations').get()).toEqual({n:0});expect(s.db.prepare('select count(*) as n from reading_positions').get()).toEqual({n:0});expect(s.db.pragma('foreign_key_check')).toEqual([]);});
