import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {afterEach,expect,it} from 'vitest';import JSZip from 'jszip';
import {openStore,createCourse,storeOriginal,readingDocument,correctMaterial,trashMaterial,type Store} from '@collegenotes/storage';
import {readingLocations,readingMatches,originalPage,locationAt,parseHash} from '@collegenotes/domain';
import {epubReading} from '@collegenotes/importers';import {createService} from '../../apps/local-service/src/index.js';
const stores:Store[]=[];afterEach(()=>{for(const s of stores.splice(0)){s.db.close();fs.rmSync(s.dataDir,{recursive:true,force:true});}});
function setup(text='First page\n\nRepeated phrase. Repeated phrase.'){const s=openStore(fs.mkdtempSync(path.join(os.tmpdir(),'cn-reading-')));stores.push(s);const c=createCourse(s,'Synthetic reading');const m=storeOriginal(s,c.id,'sample.txt',Buffer.from(text));s.db.prepare("insert into material_revisions values (?,?,1,?,?,'extraction',?)").run(m.id,c.id,text,JSON.stringify([{type:'page',locator:'page:1',textStart:0,textEnd:12},{type:'page',locator:'page:2',textStart:12,textEnd:text.length}]),m.createdAt);return {s,c,m};}
it('CHK-7.1-01 preserves exact page offsets and discloses correction alignment loss',()=>{const {s,c,m}=setup();const d=readingDocument(s,c.id,m.id);expect(d.locations.map(originalPage)).toEqual([1,2]);expect(locationAt(d.locations,13)?.start).toBe(12);correctMaterial(s,c.id,m.id,{expectedRevision:1,text:'Corrected'});expect(readingDocument(s,c.id,m.id).exactOriginalMapping).toBe(false);expect(readingDocument(s,c.id,m.id,1).text).toContain('Repeated');});
it('CHK-7.1-02 bounded passages preserve Unicode and layout characters across pagination',()=>{const text='a'.repeat(3999)+'😀\n\tTABLE\n'+ 'z'.repeat(9000);const ls=readingLocations(text,[],false);expect(ls.map(l=>text.slice(l.start,l.end)).join('')).toBe(text);expect(ls.every(l=>l.end-l.start<=4000)).toBe(true);expect(ls[0]?.end).toBe(3999);});
it('CHK-7.1-03 navigation targets and repeated search occurrences have exact offsets',()=>{expect(parseHash('#/courses/a/reading',['a']).route).toEqual({name:'reading',courseId:'a'});expect(readingMatches('İ REPEAT repeat','repeat')).toEqual([{start:2,end:8},{start:9,end:15}]);expect(readingMatches('a.b axb','a.b')).toEqual([{start:0,end:3}]);});
it('CHK-7.1-04 large documents page without dropping or duplicating source text',()=>{const text='0123456789'.repeat(200000);const ls=readingLocations(text,[],false);expect(ls).toHaveLength(500);expect(ls.map(l=>text.slice(l.start,l.end)).join('')).toBe(text);expect(readingMatches(text,'01')).toHaveLength(100);});
it('CHK-7.1-05 safe EPUB preserves table structure and blocks active/remote content',async()=>{const zip=new JSZip();zip.file('mimetype','application/epub+zip');zip.file('META-INF/container.xml','<container><rootfile full-path="book.opf"/></container>');zip.file('book.opf','<package><manifest><item id="a" href="a.xhtml"/></manifest><spine><itemref idref="a"/></spine></package>');zip.file('a.xhtml','<html><body><h1>Title</h1><script>secret()</script><table><tr><td>42</td></tr></table><img src="https://example.com/tracker" onload="evil()" alt="Figure"/></body></html>');const out=await epubReading(await zip.generateAsync({type:'nodebuffer'}));expect(out.chapters[0]?.html).toContain('<table><tr><td>42</td></tr></table>');expect(out.chapters[0]?.html).toContain('Image unavailable');expect(out.chapters[0]?.html).not.toMatch(/secret|https:|onload/);expect(out.warnings[0]).toContain('excluded');});
it('reader API rejects foreign, trashed and missing revisions',async()=>{const {s,c,m}=setup();const app=createService(s);try{expect((await app.inject(`/courses/${c.id}/reading/${m.id}`)).statusCode).toBe(200);expect((await app.inject(`/courses/${c.id}/reading/${m.id}?revision=2`)).statusCode).toBe(404);const other=createCourse(s,'Other');expect((await app.inject(`/courses/${other.id}/reading/${m.id}`)).statusCode).toBe(404);trashMaterial(s,c.id,m.id);expect((await app.inject(`/courses/${c.id}/reading/${m.id}`)).statusCode).toBe(404);}finally{await app.close();}});
