import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {afterEach,expect,it} from 'vitest';
import {openStore,createCourse,setCourseModule,storeOriginal,approveMaterial,createActivity,startAttempt,getAttempt,updateAttempt,studyAttempts,correctMaterial,type Store} from '@collegenotes/storage';
const stores:Store[]=[];afterEach(()=>{for(const s of stores.splice(0)){if(s.db.open)s.db.close();fs.rmSync(s.dataDir,{recursive:true,force:true});}});
function fixture(){const s=openStore(fs.mkdtempSync(path.join(os.tmpdir(),'cn-attempt-')));stores.push(s);const c=createCourse(s,'Synthetic reasoning');setCourseModule(s,c.id,'study',true);const m=storeOriginal(s,c.id,'text.txt',Buffer.from('Ice is solid.'));s.db.prepare("insert into material_revisions values (?,?,1,?,'[]','extraction',?)").run(m.id,c.id,'Ice is solid.',m.createdAt);approveMaterial(s,c.id,m.id,{expectedRevision:1,reviewed:true});const a=createActivity(s,c.id,{schemaVersion:1,kind:'recall',title:'Ice',prompt:'Describe ice',items:[],choices:[],answer:['solid'],rationale:'The source identifies its state.',rubric:['Identify the state.','Explain using evidence.'],hints:['Think about states.','Compare liquid and solid.'],sources:[{sourceId:m.id,revision:1,start:0,end:13,quote:'Ice is solid.'}],provenance:{kind:'user',providerId:null,modelId:null},needsReview:false});return{s,c,m,a};}
it('CHK-9.2-01 answers require submission and explicit reveal; hints advance one at a time',()=>{const{s,c,a}=fixture();let v=startAttempt(s,c.id,a.id);expect(v.solution).toBeNull();expect(v.activity).not.toHaveProperty('answer');expect(v.visibleHints).toEqual([]);expect(()=>updateAttempt(s,c.id,v.attempt.id,'reveal',{version:1})).toThrow('attempt_before_reveal');v=updateAttempt(s,c.id,v.attempt.id,'hint',{version:1});expect(v.visibleHints).toEqual(['Think about states.']);v=updateAttempt(s,c.id,v.attempt.id,'save',{version:v.attempt.version,response:['solid'],teachBack:'It holds shape.'});v=updateAttempt(s,c.id,v.attempt.id,'submit',{version:v.attempt.version});expect(v.solution).toBeNull();v=updateAttempt(s,c.id,v.attempt.id,'reveal',{version:v.attempt.version});expect(v.solution?.answer).toEqual(['solid']);});
it('CHK-9.2-02 draft and teach-back survive restart, conflicts cannot overwrite work',()=>{const{s,c,a}=fixture();let v=startAttempt(s,c.id,a.id);v=updateAttempt(s,c.id,v.attempt.id,'save',{version:1,response:['my words'],teachBack:'My explanation'});expect(()=>updateAttempt(s,c.id,v.attempt.id,'save',{version:1,response:['stale'],teachBack:''})).toThrow('attempt_version_conflict');s.db.close();const reopened=openStore(s.dataDir);s.db=reopened.db;expect(getAttempt(s,c.id,v.attempt.id).attempt).toMatchObject({response:['my words'],teachBack:'My explanation',version:2});});
it('CHK-9.2-03 feedback addresses the prepared rubric',()=>{const{s,c,a}=fixture();let v=startAttempt(s,c.id,a.id);v=updateAttempt(s,c.id,v.attempt.id,'save',{version:1,response:['solid'],teachBack:'because of its shape'});v=updateAttempt(s,c.id,v.attempt.id,'submit',{version:v.attempt.version});expect(v.attempt.feedback?.rubric).toEqual(a.rubric);});
it('CHK-9.2-04 uncertain explanation assessment is never a grade',()=>{const{s,c,a}=fixture();let v=startAttempt(s,c.id,a.id);v=updateAttempt(s,c.id,v.attempt.id,'save',{version:1,response:['different wording'],teachBack:''});v=updateAttempt(s,c.id,v.attempt.id,'submit',{version:v.attempt.version});expect(v.attempt.feedback).toMatchObject({outcome:'needs_review',score:null,authoritativeGrade:false});});
it('CHK-9.2-05 retries are fresh independent attempts and duplicate submissions are idempotent',()=>{const{s,c,a}=fixture();let v=startAttempt(s,c.id,a.id);v=updateAttempt(s,c.id,v.attempt.id,'save',{version:1,response:['solid'],teachBack:'Reason'});const submitted=updateAttempt(s,c.id,v.attempt.id,'submit',{version:v.attempt.version});expect(updateAttempt(s,c.id,v.attempt.id,'submit',{version:1})).toEqual(submitted);const retry=startAttempt(s,c.id,a.id);expect(retry.attempt.id).not.toBe(v.attempt.id);expect(retry.attempt.response).toEqual(['']);expect(retry.attempt.hintCount).toBe(0);expect(studyAttempts(s,c.id)).toHaveLength(2);});
it('attempt access is course scoped and correction blocks old attempts',()=>{const{s,c,a,m}=fixture();const v=startAttempt(s,c.id,a.id);const other=createCourse(s,'Other');setCourseModule(s,other.id,'study',true);expect(()=>getAttempt(s,other.id,v.attempt.id)).toThrow('attempt_unavailable');correctMaterial(s,c.id,m.id,{text:'Changed',expectedRevision:1});expect(()=>getAttempt(s,c.id,v.attempt.id)).toThrow('activity_needs_rebuild');});
it('prediction requires an explanation and preserves it without claiming a grade',()=>{const{s,c,a}=fixture();const prediction=createActivity(s,c.id,{...a,kind:'prediction'});let v=startAttempt(s,c.id,prediction.id);v=updateAttempt(s,c.id,v.attempt.id,'save',{version:1,response:['It will melt'],teachBack:''});expect(()=>updateAttempt(s,c.id,v.attempt.id,'submit',{version:v.attempt.version})).toThrow('prediction_explanation_required');v=updateAttempt(s,c.id,v.attempt.id,'save',{version:v.attempt.version,response:['It will melt'],teachBack:'I predict a change of state with heating.'});v=updateAttempt(s,c.id,v.attempt.id,'submit',{version:v.attempt.version});expect(v.attempt.feedback?.outcome).toBe('needs_review');expect(v.attempt.teachBack).toContain('heating');});
