import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { afterEach, expect, it } from 'vitest';
import { openStore, createCourse, setCourseModule, storeOriginal, approveMaterial, createActivity, listActivities, correctMaterial, trashMaterial, deleteMaterial, deleteCourse, exportCourse, requireActivity, type Store } from '@collegenotes/storage';
import { parseActivity, scoreActivity } from '@collegenotes/learning';
import type { ActivityTemplate } from '@collegenotes/domain';
const stores: Store[]=[];
afterEach(()=>{for(const s of stores.splice(0)){s.db.close();fs.rmSync(s.dataDir,{recursive:true,force:true});}});
function fixture(){const s=openStore(fs.mkdtempSync(path.join(os.tmpdir(),'cn-study-')));stores.push(s);const c=createCourse(s,'Synthetic study');setCourseModule(s,c.id,'study',true);const text='Water freezes at zero degrees Celsius under standard conditions.';const m=storeOriginal(s,c.id,'synthetic.txt',Buffer.from(text));s.db.prepare("insert into material_revisions values (?,?,1,?,'[]','extraction',?)").run(m.id,c.id,text,m.createdAt);approveMaterial(s,c.id,m.id,{expectedRevision:1,reviewed:true});const t:ActivityTemplate={schemaVersion:1,kind:'multiple_choice',title:'Freezing',prompt:'Which temperature?',items:[],choices:['zero','one hundred'],answer:['zero'],rationale:'The source states zero.',rubric:['Identify the temperature and conditions.'],hints:['Look for the phase change.','Use Celsius.'],sources:[{sourceId:m.id,revision:1,start:0,end:text.length,quote:text}],provenance:{kind:'user',providerId:null,modelId:null},needsReview:false};return {s,c,m,t};}
it('CHK-9.1-01 rejects malformed templates and invalid choices',()=>{const {t}=fixture();for(const bad of [{...t,schemaVersion:2},{...t,answer:['missing']},{...t,choices:['zero','zero']},{...t,sources:[]},{...t,provenance:{kind:'model'}},{...t,kind:'code'}])expect(()=>parseActivity(bad)).toThrow();});
it('CHK-9.1-02 validates exact approved course source anchors and persists provenance',()=>{const {s,c,m,t}=fixture();const a=createActivity(s,c.id,t);expect(listActivities(s,c.id)[0]).toEqual(a);expect(()=>createActivity(s,c.id,{...t,sources:[{...t.sources[0],quote:'invented'}]})).toThrow('activity_source_mismatch');const other=createCourse(s,'Other');setCourseModule(s,other.id,'study',true);expect(()=>createActivity(s,other.id,t)).toThrow('material_unavailable');expect(()=>createActivity(s,c.id,{...t,sources:[{...t.sources[0],revision:2}]})).toThrow();expect(exportCourse(s,c.id).data.records.study_activities).toHaveLength(1);expect(a.sources[0]?.sourceId).toBe(m.id);});
it('CHK-9.1-03 scores choice, ordering, classification, matching and leaves free text to review',()=>{const {t}=fixture();expect(scoreActivity(t,['zero']).score).toBe(1);expect(scoreActivity(t,['one hundred']).score).toBe(0);for(const kind of ['classification','evidence_matching'] as const){const a=parseActivity({...t,kind,items:['ice','steam'],choices:['solid','gas'],answer:['solid','gas']});expect(scoreActivity(a,['solid','gas']).score).toBe(1);expect(scoreActivity(a,['gas','gas']).score).toBe(.5);}const order=parseActivity({...t,kind:'ordering',items:['first','last'],choices:[],answer:['first','last']});expect(scoreActivity(order,['last','first']).score).toBe(0);for(const kind of ['recall','prediction'] as const)expect(scoreActivity(parseActivity({...t,kind,choices:[]}),['my explanation']).score).toBeNull();expect(()=>scoreActivity(t,[])).toThrow();});
it('CHK-9.1-04 ambiguous items require review rather than claiming correctness',()=>{const {t}=fixture();expect(scoreActivity({...t,needsReview:true},['zero'])).toMatchObject({outcome:'needs_review',score:null,authoritativeGrade:false});});
it('CHK-9.1-05 correction/trash invalidates activities and permanent deletion removes derivatives',()=>{const {s,c,m,t}=fixture();const a=createActivity(s,c.id,t);correctMaterial(s,c.id,m.id,{text:'Updated source',expectedRevision:1});expect(()=>requireActivity(s,c.id,a.id)).toThrow('activity_needs_rebuild');expect(listActivities(s,c.id)[0]?.status).toBe('stale');deleteMaterial(s,c.id,m.id,{confirmation:m.filename,backupsAcknowledged:true});expect(listActivities(s,c.id)).toEqual([]);deleteCourse(s,c.id,{confirmation:c.name,backupsAcknowledged:true});expect(s.db.prepare('select * from study_sources').all()).toEqual([]);});
it('trash and module disable retain learning data without allowing use',()=>{const {s,c,m,t}=fixture();createActivity(s,c.id,t);trashMaterial(s,c.id,m.id);expect(listActivities(s,c.id)[0]?.status).toBe('stale');setCourseModule(s,c.id,'study',false);expect(()=>listActivities(s,c.id)).toThrow('study_module_disabled');});
