import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {afterEach,expect,it} from 'vitest';
import {openStore,createCourse,setCourseModule,storeOriginal,approveMaterial,createActivity,startAttempt,updateAttempt,studyProgress,setStudyWorkload,resetReview,setSession,type Store} from '@collegenotes/storage';
import {nextReview} from '@collegenotes/learning';
const stores:Store[]=[];afterEach(()=>{for(const s of stores.splice(0)){s.db.close();fs.rmSync(s.dataDir,{recursive:true,force:true});}});
function fixture(){const s=openStore(fs.mkdtempSync(path.join(os.tmpdir(),'cn-review-')));stores.push(s);const c=createCourse(s,'Synthetic review');setCourseModule(s,c.id,'study',true);const m=storeOriginal(s,c.id,'text.txt',Buffer.from('Ice is solid.'));s.db.prepare("insert into material_revisions values (?,?,1,?,'[]','extraction',?)").run(m.id,c.id,'Ice is solid.',m.createdAt);approveMaterial(s,c.id,m.id,{expectedRevision:1,reviewed:true});const a=createActivity(s,c.id,{schemaVersion:1,kind:'multiple_choice',title:'Ice',prompt:'State?',items:[],choices:['solid','gas'],answer:['solid'],rationale:'Source evidence',rubric:['State'],hints:['Think of frozen water'],sources:[{sourceId:m.id,revision:1,start:0,end:13,quote:'Ice is solid.'}],provenance:{kind:'user',providerId:null,modelId:null},needsReview:false});return{s,c,a};}
function submit(f:ReturnType<typeof fixture>,now:string,answer='solid',hint=false){let v=startAttempt(f.s,f.c.id,f.a.id);if(hint)v=updateAttempt(f.s,f.c.id,v.attempt.id,'hint',{version:v.attempt.version});v=updateAttempt(f.s,f.c.id,v.attempt.id,'save',{version:v.attempt.version,response:[answer],teachBack:''});return updateAttempt(f.s,f.c.id,v.attempt.id,'submit',{version:v.attempt.version},now);}
it('CHK-9.3-01 UTC midnight, leap year and DST boundaries use elapsed days',()=>{const feedback={outcome:'correct' as const,score:1,message:'',rubric:[],authoritativeGrade:false as const};expect(nextReview('2028-02-28T23:59:59.000Z',0,feedback,false).dueAt).toBe('2028-02-29T23:59:59.000Z');expect(nextReview('2026-03-08T01:30:00-07:00',0,feedback,false).dueAt).toBe('2026-03-09T08:30:00.000Z');expect(()=>nextReview('invalid',0,feedback,false)).toThrow();const f=fixture();submit(f,'2026-12-31T23:59:59.000Z');expect(studyProgress(f.s,f.c.id,'2027-01-01T23:59:58.000Z').dueTotal).toBe(0);expect(studyProgress(f.s,f.c.id,'2027-01-01T23:59:59.000Z').dueTotal).toBe(1);});
it('CHK-9.3-02 missed days preserve due work without penalty and workload is bounded',()=>{const f=fixture();submit(f,'2026-09-20T10:00:00.000Z');setStudyWorkload(f.s,f.c.id,{dailyLimit:1});const p=studyProgress(f.s,f.c.id,'2026-10-20T10:00:00.000Z');expect(p.due).toHaveLength(1);expect(p.due[0]?.intervalDays).toBe(1);expect(p.correctUnaided).toBe(1);expect(()=>setStudyWorkload(f.s,f.c.id,{dailyLimit:0})).toThrow();});
it('CHK-9.3-03 repeated attempts schedule from evidence and duplicate replay adds no credit',()=>{const f=fixture();const v=submit(f,'2026-09-20T10:00:00.000Z');updateAttempt(f.s,f.c.id,v.attempt.id,'submit',{version:1},'2026-09-21T10:00:00.000Z');expect(studyProgress(f.s,f.c.id).submitted).toBe(1);submit(f,'2026-09-21T10:00:00.000Z');expect(studyProgress(f.s,f.c.id,'2026-10-01T00:00:00.000Z').due[0]?.intervalDays).toBe(2);submit(f,'2026-09-22T10:00:00.000Z','gas');expect(studyProgress(f.s,f.c.id,'2026-10-01T00:00:00.000Z').due[0]?.intervalDays).toBe(1);submit(f,'2026-09-23T10:00:00.000Z','solid',true);expect(studyProgress(f.s,f.c.id,'2026-10-01T00:00:00.000Z').assisted).toBe(1);});
it('CHK-9.3-04 reset and undo preserve attempts; subsequent learning invalidates undo',()=>{const f=fixture();submit(f,'2026-09-20T10:00:00.000Z');const before=studyProgress(f.s,f.c.id,'2026-09-20T12:00:00.000Z');expect(resetReview(f.s,f.c.id,f.a.id,false,'2026-09-20T12:00:00.000Z').dueTotal).toBe(1);expect(resetReview(f.s,f.c.id,f.a.id,true,'2026-09-20T12:00:00.000Z').dueTotal).toBe(before.dueTotal);expect(studyProgress(f.s,f.c.id).submitted).toBe(1);resetReview(f.s,f.c.id,f.a.id,false);submit(f,'2026-09-21T10:00:00.000Z');expect(()=>resetReview(f.s,f.c.id,f.a.id,true)).toThrow('review_undo_unavailable');});
it('CHK-9.3-05 reading position or elapsed time never creates recall or mastery evidence',()=>{const f=fixture();setSession(f.s,{courseId:f.c.id,routeHash:`#/courses/${f.c.id}/reading`,task:'reading',notice:null});const p=studyProgress(f.s,f.c.id,'2030-01-01T00:00:00.000Z');expect(p.submitted).toBe(0);expect(p.correctUnaided).toBe(0);expect(p).not.toHaveProperty('mastery');});
